In [1]:
import numpy as np
import zebende as zb
import pandas as pd

In [2]:
tws = pd.read_csv('./test_data/time_window_scales.txt', header=None).to_numpy().flatten()[:3]
tws

array([4, 5, 7])

In [3]:
data_1 = pd.read_csv('./test_data/data_pre_proc/S001/S001_03/S001_03_F3.txt', header=None)
data_2 = pd.read_csv('./test_data/data_pre_proc/S001/S001_03/S001_03_F6.txt', header=None)
data_3 = pd.read_csv('./test_data/data_pre_proc/S001/S001_03/S001_03_P3.txt', header=None)
data_4 = pd.read_csv('./test_data/data_pre_proc/S001/S001_03/S001_03_P6.txt', header=None)

In [4]:
data = pd.concat([data_1, data_2, data_3, data_4], axis=1).to_numpy(dtype=np.float64)
data

array([[-28., -57., -43., -52.],
       [-32., -67., -67., -60.],
       [-44., -74., -74., -66.],
       ...,
       [-15., -54., -59., -57.],
       [  0., -41., -25., -47.],
       [-15., -48., -50., -72.]])

In [5]:
int_data = zb.integrated_series(data)
int_data

array([[-2.34179266e+01, -5.31401347e+01, -4.23017406e+01,
        -4.93068860e+01],
       [-5.08358531e+01, -1.16280269e+02, -1.08603481e+02,
        -1.06613772e+02],
       [-9.02537797e+01, -1.86420404e+02, -1.81905222e+02,
        -1.69920658e+02],
       ...,
       [ 5.83585313e+00,  8.12802693e+01,  7.36034811e+01,
         1.13613772e+02],
       [ 1.04179266e+01,  4.41401347e+01,  4.93017406e+01,
         6.93068860e+01],
       [-2.77380252e-09, -1.07685594e-09, -2.15914042e-09,
         1.08613563e-10]])

In [6]:
dfa , dcca, pdcca = zb.p_dcca(int_data, tws)

In [ ]:
[[1, 2,0,3,4], [2,0,1,3,4]]

In [7]:
dfa_2 , dcca_2, pdcca_2, dmc = zb.dmcx2(int_data, tws, dmcx2_of='all-full')

[[1.         0.47030178 0.45810527]
 [0.47030178 1.         0.73191068]
 [0.45810527 0.73191068 1.        ]] [[0.86081923]
 [0.59896514]
 [0.49887712]]
[[1.         0.59896514 0.49887712]
 [0.59896514 1.         0.73191068]
 [0.49887712 0.73191068 1.        ]] [[0.86081923]
 [0.47030178]
 [0.45810527]]
[[1.         0.86081923 0.49887712]
 [0.86081923 1.         0.45810527]
 [0.49887712 0.45810527 1.        ]] [[0.59896514]
 [0.47030178]
 [0.73191068]]
[[1.         0.86081923 0.59896514]
 [0.86081923 1.         0.47030178]
 [0.59896514 0.47030178 1.        ]] [[0.49887712]
 [0.45810527]
 [0.73191068]]
[[1.         0.47167895 0.46036665]
 [0.47167895 1.         0.72861283]
 [0.46036665 0.72861283 1.        ]] [[0.86969829]
 [0.60025456]
 [0.50163041]]
[[1.         0.60025456 0.50163041]
 [0.60025456 1.         0.72861283]
 [0.50163041 0.72861283 1.        ]] [[0.86969829]
 [0.47167895]
 [0.46036665]]
[[1.         0.86969829 0.50163041]
 [0.86969829 1.         0.46036665]
 [0.50163041 0.4

In [8]:
dfa_2

array([[10.21772684,  9.6465587 , 11.1907025 ,  9.96204291],
       [13.54907402, 12.58526165, 14.79349141, 12.92467481],
       [20.64787156, 18.7922314 , 22.42865193, 19.17401719]])

In [9]:
pdcca

array([[0.86081923, 0.59896514, 0.49887712, 0.47030178, 0.45810527,
        0.73191068],
       [0.86969829, 0.60025456, 0.50163041, 0.47167895, 0.46036665,
        0.72861283],
       [0.88369784, 0.61011439, 0.51609336, 0.48228142, 0.47344466,
        0.73597588]])

In [10]:
pdcca_2.shape

(4, 4, 3)

In [11]:
pdcca_2.transpose(2,0,1)

array([[[1.        , 0.86081923, 0.59896514, 0.49887712],
        [0.86081923, 1.        , 0.47030178, 0.45810527],
        [0.59896514, 0.47030178, 1.        , 0.73191068],
        [0.49887712, 0.45810527, 0.73191068, 1.        ]],

       [[1.        , 0.86969829, 0.60025456, 0.50163041],
        [0.86969829, 1.        , 0.47167895, 0.46036665],
        [0.60025456, 0.47167895, 1.        , 0.72861283],
        [0.50163041, 0.46036665, 0.72861283, 1.        ]],

       [[1.        , 0.88369784, 0.61011439, 0.51609336],
        [0.88369784, 1.        , 0.48228142, 0.47344466],
        [0.61011439, 0.48228142, 1.        , 0.73597588],
        [0.51609336, 0.47344466, 0.73597588, 1.        ]]])

In [12]:
dmc

array([[0.7907023 , 0.7518667 , 0.6233089 , 0.55512699],
       [0.80407253, 0.76754982, 0.62145434, 0.55125401],
       [0.82630671, 0.79290835, 0.63437872, 0.56323711]])

[[1.         0.47030178 0.45810527]
 [0.47030178 1.         0.73191068]
 [0.45810527 0.73191068 1.        ]] [[0.86081923 0.59896514 0.49887712]]
[[1.         0.47167895 0.46036665]
 [0.47167895 1.         0.72861283]
 [0.46036665 0.72861283 1.        ]] [[0.86969829 0.60025456 0.50163041]]
[[1.         0.48228142 0.47344466]
 [0.48228142 1.         0.73597588]
 [0.47344466 0.73597588 1.        ]] [[0.88369784 0.61011439 0.51609336]]
[[1.         0.49090246 0.48644053]
 [0.49090246 1.         0.74985759]
 [0.48644053 0.74985759 1.        ]] [[0.89272374 0.62040214 0.53288603]]
[[1.         0.49594519 0.49773076]
 [0.49594519 1.         0.76465074]
 [0.49773076 0.76465074 1.        ]] [[0.89828945 0.62875523 0.54880357]]


In [13]:
rnd = 4
result_check = pd.read_csv('test_data/data_proc/S001/S001_03/S001_03_DMCX2_F3_F6_P3_P6.txt',sep=' ', header=None,index_col=0, dtype=np.float64).head(dmc[:,0].size).to_numpy().flatten().round(rnd)
result_check, result_check == dmc[:,0].round(rnd )

(array([0.7907, 0.8041, 0.8263]), array([ True,  True,  True]))

In [14]:
if (result_check == dmc[:,0].round(rnd)).all() == True:
    print('pass')
else:
    print('found diference')


pass


In [15]:
dmc

array([[0.7907023 , 0.7518667 , 0.6233089 , 0.55512699],
       [0.80407253, 0.76754982, 0.62145434, 0.55125401],
       [0.82630671, 0.79290835, 0.63437872, 0.56323711]])