In [2]:
import numpy as np
#import pandas as pd
import zebende as zb


In [4]:
mat = np.random.random(size=(800,8))
mat

array([[0.46869295, 0.45783338, 0.96314045, ..., 0.67622585, 0.89380787,
        0.26148929],
       [0.8862231 , 0.74697608, 0.66292002, ..., 0.34542921, 0.02532101,
        0.65964872],
       [0.40097435, 0.59286011, 0.00383454, ..., 0.58523801, 0.14984591,
        0.18421591],
       ...,
       [0.22904445, 0.36943097, 0.13774048, ..., 0.64757298, 0.94850088,
        0.79670453],
       [0.30957198, 0.71942439, 0.90369766, ..., 0.65902746, 0.3805323 ,
        0.13831935],
       [0.86256313, 0.94820645, 0.82151204, ..., 0.28331856, 0.64517896,
        0.32150579]])

In [5]:
int_mat = zb.integrated_series(mat)
print(int_mat)

[[-2.45475127e-02 -4.08657489e-02  4.65605450e-01 ...  1.86474678e-01
   3.81746386e-01 -2.41797390e-01]
 [ 3.68435116e-01  2.07411204e-01  6.30990478e-01 ...  4.21527181e-02
  -1.04994081e-01 -8.54353525e-02]
 [ 2.76169001e-01  3.01572184e-01  1.37290018e-01 ...  1.37639558e-01
  -4.67209648e-01 -4.04506122e-01]
 ...
 [-1.85654178e-01 -6.70232577e-01 -7.30139707e-01 ...  3.71563164e-02
  -1.58830099e-03  5.46748210e-01]
 [-3.69322660e-01 -4.49507315e-01 -3.23977039e-01 ...  2.06432610e-01
  -1.33117478e-01  1.81780884e-01]
 [ 5.77315973e-15  1.39110945e-13  3.73701070e-13 ...  2.84550161e-13
  -9.62563362e-14  2.81996648e-14]]


In [6]:
tws = zb.time_windows(4, 200)
tws

array([  4,   5,   7,   9,  11,  13,  16,  20,  24,  28,  33,  38,  45,
        52,  60,  69,  80,  91, 104, 119, 135, 154, 174, 198, 200])

In [7]:
F_DFA, DCCA, P_DCCA = zb.p_dcca(int_mat, tws)

In [8]:
F_DFA

array([[0.15566165, 0.15053656, 0.15137936, 0.15072539, 0.1549096 ,
        0.15203657, 0.15399532, 0.15187021],
       [0.17434358, 0.16897501, 0.17144883, 0.17098115, 0.17516575,
        0.17191536, 0.17326213, 0.17235272],
       [0.20340669, 0.199771  , 0.20387821, 0.20438323, 0.20916578,
        0.2041712 , 0.20487944, 0.20470621],
       [0.22814852, 0.22672928, 0.23020127, 0.23182136, 0.23648167,
        0.23347872, 0.23224828, 0.23039204],
       [0.25020045, 0.25202964, 0.25198288, 0.25493946, 0.26036263,
        0.2598914 , 0.25722727, 0.25379893],
       [0.27081122, 0.27633129, 0.27129373, 0.27489208, 0.28298001,
        0.28324306, 0.27960764, 0.2763523 ],
       [0.29998481, 0.30983452, 0.29869517, 0.30038875, 0.31500267,
        0.31396007, 0.30833957, 0.30706392],
       [0.3360201 , 0.3478003 , 0.33281778, 0.32947107, 0.35467617,
        0.34978822, 0.34043929, 0.34146702],
       [0.36935383, 0.37991362, 0.36447369, 0.35683456, 0.39115004,
        0.38076728, 0.368654

In [9]:
print(DCCA)

[[-9.79574728e-04  2.58748761e-04  2.28513766e-04  7.50218280e-04
  -1.02965979e-04 -5.67477787e-04 -2.42099038e-04 -1.38281553e-03
  -2.89132969e-04 -8.72271858e-05 -2.36944045e-03  4.78165615e-04
  -1.20862901e-03 -1.00453435e-03  1.43868105e-05 -1.05547054e-05
  -7.99149144e-04  7.31806461e-04 -3.99727592e-05 -2.17074504e-04
   7.31542928e-04  1.38498633e-05 -1.76830922e-04  1.42784359e-03
   1.06379412e-03 -2.05984912e-04  3.31053292e-04 -6.96137320e-05]
 [-1.23268918e-03  2.25995879e-04  6.79573704e-04  6.18092545e-04
   1.29366831e-04 -8.88414017e-04 -5.12545859e-04 -1.41461616e-03
  -3.57508728e-04 -1.31794680e-04 -2.66183128e-03  9.03640421e-04
  -1.90679235e-03 -1.41271391e-03 -9.98267145e-05  3.44473761e-04
  -1.37315444e-03  1.20911432e-03  1.59680785e-04 -2.37291930e-04
   1.02438341e-03  9.47876933e-06 -4.93028822e-04  2.14882465e-03
   1.08006005e-03 -2.66307690e-04  7.03469821e-04 -6.19776352e-05]
 [-1.53863063e-03  2.30228476e-04  1.49958316e-03  1.42223940e-04
   7.698

In [10]:
P_DCCA

array([[-4.1800e-02,  1.0980e-02,  9.7400e-03,  3.1110e-02, -4.3500e-03,
        -2.3670e-02, -1.0240e-02, -6.0680e-02, -1.2740e-02, -3.7400e-03,
        -1.0353e-01,  2.0630e-02, -5.2870e-02, -4.4030e-02,  6.1000e-04,
        -4.6000e-04, -3.4280e-02,  3.1830e-02, -1.7100e-03, -9.4700e-03,
         3.1520e-02,  6.1000e-04, -7.5100e-03,  5.9850e-02,  4.5220e-02,
        -8.8000e-03,  1.4340e-02, -2.9800e-03],
       [-4.1840e-02,  7.5600e-03,  2.2800e-02,  2.0240e-02,  4.3200e-03,
        -2.9410e-02, -1.7060e-02, -4.8830e-02, -1.2370e-02, -4.4500e-03,
        -9.1630e-02,  3.0870e-02, -6.5470e-02, -4.8190e-02, -3.3200e-03,
         1.1690e-02, -4.6230e-02,  4.0920e-02,  5.3300e-03, -8.0700e-03,
         3.4580e-02,  3.2000e-04, -1.6370e-02,  7.0800e-02,  3.5780e-02,
        -8.9400e-03,  2.3740e-02, -2.0800e-03],
       [-3.7860e-02,  5.5500e-03,  3.6070e-02,  3.3400e-03,  1.8540e-02,
        -2.4250e-02, -1.6550e-02, -3.6870e-02, -2.7120e-02, -4.6000e-03,
        -7.2410e-02,  4.6760

In [54]:
arr_tot = []

arr_1 = np.sort([2,1])
arr_2 = np.sort(np.array([2,1]))
arr_3 = np.sort(np.array([2,3]))
arr_list = [arr_1, arr_2, arr_3]
for i in arr_list:
    if   True:
        arr_tot.append(i)
    print(arr_tot)
arr_tot

[array([1, 2])]
[array([1, 2]), array([1, 2])]
[array([1, 2]), array([1, 2]), array([2, 3])]


[array([1, 2]), array([1, 2]), array([2, 3])]

In [73]:
# importing package 
import numpy as np

# create numpy array 
arr = np.array([[1, 2, 3, 4, 5], 
				[6, 7, 8, 9, 10], 
				[11, 12, 13, 14, 15], 
				[16, 17, 18, 19, 20] 
				]) 

# view array 
print(np.array(arr.tolist())) 

# check for some lists 
print([1, 2, 3, 4, 5] in arr.tolist()) 
print([16, 17, 20, 19, 18] in arr.tolist()) 
print([3, 2, 5, -4, 5] in arr.tolist()) 
print([11, 12, 13, 14, 15] in arr.tolist()) 


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
True
False
False
True


In [68]:
arr = np.random.randint(10, size=(4,8))

In [69]:
arr

array([[9, 0, 0, 2, 6, 7, 6, 8],
       [1, 2, 2, 6, 5, 5, 7, 5],
       [2, 1, 9, 1, 1, 6, 1, 8],
       [1, 6, 9, 6, 7, 9, 9, 2]], dtype=int32)

In [70]:
arr.sort()

In [216]:
from itertools import combinations
import numpy as np


def pdcca_of_from_dmcx2_of(dmc_of):
    if type(dmc_of) == np.ndarray:
        dmc_of = dmc_of.tolist()
    out = []
    for i in range(len(dmc_of)):
        temp = list(combinations(dmc_of[i],2))
        for j in temp:
            j = list(j)

            j.sort()

            if not(j in out):
                out.append(j)
    return np.array(out)

In [217]:
dmc_of = np.array([[1,3,4,5], [0,4,3,5]])

dmc_of.max(), dmc_of.min(), type(dmc_of)

(np.int64(5), np.int64(0), numpy.ndarray)

In [218]:
test = pdcca_of_from_dmcx2_of(dmc_of)
test,type(dmc_of)

(array([[1, 3],
        [1, 4],
        [1, 5],
        [3, 4],
        [3, 5],
        [4, 5],
        [0, 4],
        [0, 3],
        [0, 5]]),
 numpy.ndarray)

In [187]:
import numpy as np


def dcca_of_from_dmcx2_of(data):
    temp = np.arange(data.shape[1])

In [219]:
dcca_of_from_dmcx2_of(mat)

NameError: name 'mat' is not defined

In [220]:
a,b = 2
a,b

TypeError: cannot unpack non-iterable int object

In [236]:
arr = np.array([2,4,5]).reshape(1,3)
arr 

array([[2, 4, 5]])

In [235]:
mat=np.random.random(size=(3,3))
mat

ValueError: cannot reshape array of size 9 into shape (1,3)

In [243]:
np.matmul(np.matmul(arr, np.linalg.inv(mat)), arr.T)

array([[18.98096461]])

In [102]:


dmc_of=np.array([[1,2,4,3], [3,5,4,7], [4,2,3,1]])
dmc_of

array([[1, 2, 4, 3],
       [3, 5, 4, 7],
       [4, 2, 3, 1]])

In [101]:

def ordering_x_dmcx2_of(dmcx2_of):
    y_serie = dmcx2_of[:,0]
    x_series = np.sort(dmcx2_of[:, 1:], axis=1)
    print(x_series, y_serie)
    out =  np.c_[ y_serie, x_series ] 
    return out 

In [103]:
dmc =ordering_x_dmcx2_of(dmc_of)
dmc


[[2 3 4]
 [4 5 7]
 [1 2 3]] [1 3 4]


array([[1, 2, 3, 4],
       [3, 4, 5, 7],
       [4, 1, 2, 3]])