In [1]:
import numpy as np
import zebende as zb
import pandas as pd

In [2]:
tws = pd.read_csv('./test_data/time_window_scales.txt', header=None).to_numpy().flatten()[:]
tws

array([   4,    5,    7,    9,   11,   13,   16,   20,   23,   28,   33,
         38,   45,   52,   60,   69,   79,   91,  104,  119,  135,  154,
        174,  198,  223,  252,  285,  321,  362,  407,  457,  513,  575,
        645,  723,  809,  905, 1011, 1130, 1261, 1407, 1570])

In [3]:
data_1 = pd.read_csv('./test_data/data_pre_proc/S001/S001_03/S001_03_F3.txt', header=None)
data_2 = pd.read_csv('./test_data/data_pre_proc/S001/S001_03/S001_03_F6.txt', header=None)
data_3 = pd.read_csv('./test_data/data_pre_proc/S001/S001_03/S001_03_P3.txt', header=None)
data_4 = pd.read_csv('./test_data/data_pre_proc/S001/S001_03/S001_03_P6.txt', header=None)

In [4]:
data = pd.concat([data_1, data_2, data_3, data_4], axis=1).to_numpy(dtype=np.float64)
data

array([[-28., -57., -43., -52.],
       [-32., -67., -67., -60.],
       [-44., -74., -74., -66.],
       ...,
       [-15., -54., -59., -57.],
       [  0., -41., -25., -47.],
       [-15., -48., -50., -72.]])

In [5]:
int_data = zb.integrated_series(data)
int_data

array([[-2.34179266e+01, -5.31401347e+01, -4.23017406e+01,
        -4.93068860e+01],
       [-5.08358531e+01, -1.16280269e+02, -1.08603481e+02,
        -1.06613772e+02],
       [-9.02537797e+01, -1.86420404e+02, -1.81905222e+02,
        -1.69920658e+02],
       ...,
       [ 5.83585313e+00,  8.12802693e+01,  7.36034811e+01,
         1.13613772e+02],
       [ 1.04179266e+01,  4.41401347e+01,  4.93017406e+01,
         6.93068860e+01],
       [-2.77380252e-09, -1.07685594e-09, -2.15914042e-09,
         1.08613563e-10]])

In [6]:
dfa , dcca, pdcca = zb.p_dcca(int_data, tws)

In [7]:
dfa_2 , dcca_2, pdcca_2, dmc = zb.dmcx2(int_data, tws, dmcx2_of='all-full')

[[1.         0.47030178 0.45810527]
 [0.47030178 1.         0.73191068]
 [0.45810527 0.73191068 1.        ]] [[0.86081923]
 [0.59896514]
 [0.49887712]]
[[1.         0.73191068 0.59896514]
 [0.73191068 1.         0.49887712]
 [0.59896514 0.49887712 1.        ]] [[0.47030178]
 [0.45810527]
 [0.86081923]]
[[1.         0.86081923 0.59896514]
 [0.86081923 1.         0.47030178]
 [0.59896514 0.47030178 1.        ]] [[0.49887712]
 [0.45810527]
 [0.73191068]]
[[1.         0.49887712 0.45810527]
 [0.49887712 1.         0.86081923]
 [0.45810527 0.86081923 1.        ]] [[0.73191068]
 [0.59896514]
 [0.47030178]]
[[1.         0.47167895 0.46036665]
 [0.47167895 1.         0.72861283]
 [0.46036665 0.72861283 1.        ]] [[0.86969829]
 [0.60025456]
 [0.50163041]]
[[1.         0.72861283 0.60025456]
 [0.72861283 1.         0.50163041]
 [0.60025456 0.50163041 1.        ]] [[0.47167895]
 [0.46036665]
 [0.86969829]]
[[1.         0.86969829 0.60025456]
 [0.86969829 1.         0.47167895]
 [0.60025456 0.4

In [18]:
dfa_2

array([[  10.21772684,    9.6465587 ,   11.1907025 ,    9.96204291],
       [  13.54907402,   12.58526165,   14.79349141,   12.92467481],
       [  20.64787156,   18.7922314 ,   22.42865193,   19.17401719],
       [  28.13487765,   25.39630971,   30.27471654,   25.57855316],
       [  35.91221786,   32.38197129,   38.07809875,   31.95381504],
       [  43.95074905,   39.72966712,   45.77421069,   38.25349835],
       [  56.51314047,   51.41934765,   57.16832443,   47.5856257 ],
       [  74.36427176,   68.36098629,   72.40638486,   60.06754951],
       [  88.59690355,   82.0879886 ,   84.12931203,   69.6831767 ],
       [ 113.60133346,  106.57219865,  104.39102466,   86.29483778],
       [ 139.80076451,  132.61055344,  125.43673255,  103.52711883],
       [ 166.9606614 ,  159.86245425,  147.05497521,  121.30237516],
       [ 206.18455249,  199.44597732,  177.67034212,  146.65918013],
       [ 246.48875228,  240.11560646,  208.25353117,  172.17761595],
       [ 293.80418707,  287.440972

In [8]:
pdcca

array([[0.86081923, 0.59896514, 0.49887712, 0.47030178, 0.45810527,
        0.73191068],
       [0.86969829, 0.60025456, 0.50163041, 0.47167895, 0.46036665,
        0.72861283],
       [0.88369784, 0.61011439, 0.51609336, 0.48228142, 0.47344466,
        0.73597588],
       [0.89272374, 0.62040214, 0.53288603, 0.49090246, 0.48644053,
        0.74985759],
       [0.89828945, 0.62875523, 0.54880357, 0.49594519, 0.49773076,
        0.76465074],
       [0.90172824, 0.63601988, 0.56417735, 0.49936359, 0.50861306,
        0.77875949],
       [0.90473334, 0.64503431, 0.58540363, 0.50270925, 0.52378628,
        0.79731586],
       [0.90690709, 0.65111924, 0.60520667, 0.50267396, 0.5368762 ,
        0.81616994],
       [0.90782423, 0.65142237, 0.61306633, 0.49944187, 0.54055764,
        0.8262844 ],
       [0.90846026, 0.64794591, 0.61831274, 0.49114757, 0.54002739,
        0.83835374],
       [0.90843364, 0.64285345, 0.61882623, 0.48205819, 0.53609609,
        0.84727615],
       [0.90808789, 0

In [9]:
pdcca_2.shape

(4, 4, 42)

In [10]:
pdcca_2.transpose(2,0,1)

array([[[1.        , 0.86081923, 0.59896514, 0.49887712],
        [0.86081923, 1.        , 0.47030178, 0.45810527],
        [0.59896514, 0.47030178, 1.        , 0.73191068],
        [0.49887712, 0.45810527, 0.73191068, 1.        ]],

       [[1.        , 0.86969829, 0.60025456, 0.50163041],
        [0.86969829, 1.        , 0.47167895, 0.46036665],
        [0.60025456, 0.47167895, 1.        , 0.72861283],
        [0.50163041, 0.46036665, 0.72861283, 1.        ]],

       [[1.        , 0.88369784, 0.61011439, 0.51609336],
        [0.88369784, 1.        , 0.48228142, 0.47344466],
        [0.61011439, 0.48228142, 1.        , 0.73597588],
        [0.51609336, 0.47344466, 0.73597588, 1.        ]],

       [[1.        , 0.89272374, 0.62040214, 0.53288603],
        [0.89272374, 1.        , 0.49090246, 0.48644053],
        [0.62040214, 0.49090246, 1.        , 0.74985759],
        [0.53288603, 0.48644053, 0.74985759, 1.        ]],

       [[1.        , 0.89828945, 0.62875523, 0.54880357],
      

In [11]:
dmc

array([[0.7907023 , 0.7518667 , 0.55512699, 0.6233089 ],
       [0.80407253, 0.76754982, 0.55125401, 0.62145434],
       [0.82630671, 0.79290835, 0.56323711, 0.63437872],
       [0.8420508 , 0.81008021, 0.58435785, 0.65400007],
       [0.85292913, 0.82153414, 0.60723968, 0.67390238],
       [0.86064569, 0.82940732, 0.62975299, 0.69256377],
       [0.86869283, 0.83742984, 0.66042646, 0.71687213],
       [0.87539568, 0.84432616, 0.69229397, 0.74107022],
       [0.87840743, 0.84768211, 0.7093625 , 0.75375336],
       [0.88115729, 0.85103904, 0.72955058, 0.76879013],
       [0.88243519, 0.8528798 , 0.74447753, 0.78026748],
       [0.88291609, 0.85390047, 0.75578376, 0.78925732],
       [0.88262088, 0.85427043, 0.76679877, 0.79829909],
       [0.88154663, 0.85369096, 0.77395901, 0.80439733],
       [0.87985235, 0.8522577 , 0.77974069, 0.80962022],
       [0.87765357, 0.84990532, 0.78481285, 0.81462841],
       [0.87487143, 0.84639346, 0.78945493, 0.81967263],
       [0.8710954 , 0.84108519,

[[1.         0.47030178 0.45810527]
 [0.47030178 1.         0.73191068]
 [0.45810527 0.73191068 1.        ]] [[0.86081923 0.59896514 0.49887712]]
[[1.         0.47167895 0.46036665]
 [0.47167895 1.         0.72861283]
 [0.46036665 0.72861283 1.        ]] [[0.86969829 0.60025456 0.50163041]]
[[1.         0.48228142 0.47344466]
 [0.48228142 1.         0.73597588]
 [0.47344466 0.73597588 1.        ]] [[0.88369784 0.61011439 0.51609336]]
[[1.         0.49090246 0.48644053]
 [0.49090246 1.         0.74985759]
 [0.48644053 0.74985759 1.        ]] [[0.89272374 0.62040214 0.53288603]]
[[1.         0.49594519 0.49773076]
 [0.49594519 1.         0.76465074]
 [0.49773076 0.76465074 1.        ]] [[0.89828945 0.62875523 0.54880357]]


In [16]:
rnd = 4
result_check = pd.read_csv('test_data/data_proc/S001/S001_03/S001_03_DMCX2_F3_F6_P3_P6.txt',sep=' ', header=None,index_col=0, dtype=np.float64).head(dmc[:,0].size).to_numpy().flatten().round(rnd)
result_check, result_check == dmc[:,0].round(rnd )

(array([0.7907, 0.8041, 0.8263, 0.8421, 0.8529, 0.8607, 0.8687, 0.8754,
        0.8784, 0.8812, 0.8824, 0.8829, 0.8826, 0.8815, 0.8799, 0.8777,
        0.8749, 0.8711, 0.8666, 0.8611, 0.8552, 0.8482, 0.8407, 0.8317,
        0.8225, 0.8124, 0.8016, 0.7905, 0.778 , 0.7643, 0.7504, 0.7366,
        0.7218, 0.7046, 0.684 , 0.659 , 0.6301, 0.599 , 0.5674, 0.5405,
        0.52  , 0.5041]),
 array([ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True, False, False, False,
        False,  True, False,  True,  True,  True]))

In [13]:
if (result_check == dmc[:,0].round(rnd)).all() == True:
    print('pass')
else:
    print('found diference')


pass


In [14]:
dmc

array([[0.7907023 , 0.7518667 , 0.55512699, 0.6233089 ],
       [0.80407253, 0.76754982, 0.55125401, 0.62145434],
       [0.82630671, 0.79290835, 0.56323711, 0.63437872],
       [0.8420508 , 0.81008021, 0.58435785, 0.65400007],
       [0.85292913, 0.82153414, 0.60723968, 0.67390238],
       [0.86064569, 0.82940732, 0.62975299, 0.69256377],
       [0.86869283, 0.83742984, 0.66042646, 0.71687213],
       [0.87539568, 0.84432616, 0.69229397, 0.74107022],
       [0.87840743, 0.84768211, 0.7093625 , 0.75375336],
       [0.88115729, 0.85103904, 0.72955058, 0.76879013],
       [0.88243519, 0.8528798 , 0.74447753, 0.78026748],
       [0.88291609, 0.85390047, 0.75578376, 0.78925732],
       [0.88262088, 0.85427043, 0.76679877, 0.79829909],
       [0.88154663, 0.85369096, 0.77395901, 0.80439733],
       [0.87985235, 0.8522577 , 0.77974069, 0.80962022],
       [0.87765357, 0.84990532, 0.78481285, 0.81462841],
       [0.87487143, 0.84639346, 0.78945493, 0.81967263],
       [0.8710954 , 0.84108519,