In [1]:
import numpy as np
import zebende as zb
import pandas as pd

In [2]:
dmcx2_of = np.array([[7,2,3,4,5], [0,2,1,3,5]])

In [ ]:
dmcx2_of = np.array([0,2,1,3,5])

In [ ]:
dmcx2_of

In [3]:
zb.ordering_x_dmcx2_of(dmcx2_of)

<class 'numpy.ndarray'>


array([[7, 2, 3, 4, 5],
       [0, 1, 2, 3, 5]])

In [ ]:
tws = pd.read_csv('./test_data/time_window_scales.txt', header=None).to_numpy().flatten()
tws

In [ ]:
data_1 = pd.read_csv('./test_data/data_pre_proc/S001/S001_03/S001_03_F3.txt', header=None)
data_2 = pd.read_csv('./test_data/data_pre_proc/S001/S001_03/S001_03_F6.txt', header=None)
data_3 = pd.read_csv('./test_data/data_pre_proc/S001/S001_03/S001_03_P3.txt', header=None)
data_4 = pd.read_csv('./test_data/data_pre_proc/S001/S001_03/S001_03_P6.txt', header=None)

In [ ]:
data = pd.concat([data_1, data_2, data_3, data_4], axis=1)
data.to_csv('./test_data/data_pre_proc/S001/four_channels.csv')

In [ ]:
data.tail()

In [ ]:
data = data.to_numpy()
data

In [ ]:
int_data = zb.integrated_series(data)
int_data.shape[0]

In [ ]:
dfa , dcca, pdcca = zb.p_dcca(int_data, tws)

In [ ]:
pdcca.shape

In [ ]:
dcca_of = zb.mat_index_comb(int_data, axis=1)

In [ ]:
mat_pdcca = zb.p_dcca_simple_to_matrix(pdcca, DCCA_of=dcca_of)
mat_pdcca.shape

In [ ]:
dfa_2 , dcca_2, pdcca_2, dmc = zb.dmcx2(int_data, tws, dmcx2_of='all-full')

In [ ]:
pdcca_2.shape

In [ ]:
(mat_pdcca ==  pdcca_2).all()

In [ ]:
pdcca_3 = zb.p_dcca_matrix_to_simple(mat_pdcca)
(pdcca ==  pdcca_3).all()

In [ ]:
dfa_2

In [ ]:
pdcca

In [ ]:
pdcca_2.transpose(2,0,1)

In [ ]:
dmc

[[1.         0.47030178 0.45810527]
 [0.47030178 1.         0.73191068]
 [0.45810527 0.73191068 1.        ]] [[0.86081923 0.59896514 0.49887712]]
[[1.         0.47167895 0.46036665]
 [0.47167895 1.         0.72861283]
 [0.46036665 0.72861283 1.        ]] [[0.86969829 0.60025456 0.50163041]]
[[1.         0.48228142 0.47344466]
 [0.48228142 1.         0.73597588]
 [0.47344466 0.73597588 1.        ]] [[0.88369784 0.61011439 0.51609336]]
[[1.         0.49090246 0.48644053]
 [0.49090246 1.         0.74985759]
 [0.48644053 0.74985759 1.        ]] [[0.89272374 0.62040214 0.53288603]]
[[1.         0.49594519 0.49773076]
 [0.49594519 1.         0.76465074]
 [0.49773076 0.76465074 1.        ]] [[0.89828945 0.62875523 0.54880357]]


In [ ]:
rnd = 3
result_check = pd.read_csv('test_data/data_proc/S001/S001_03/S001_03_DMCX2_F3_F6_P3_P6.txt',sep=' ', header=None,index_col=0, dtype=np.float64).head(dmc[:,0].size).to_numpy().flatten().round(rnd)
result_check, result_check == dmc[:,0].round(rnd )

In [ ]:
if (result_check == dmc[:,0].round(rnd)).all() == True:
    print('pass')
else:
    print('found diference')


In [ ]:
dmc

In [ ]:
np.__version__