In [1]:
import numpy as np
#import pandas as pd
import zebende as zb


In [2]:
mat = np.random.random(size=(20_000,8))
mat

array([[0.81475118, 0.36157644, 0.71797706, ..., 0.24162542, 0.78903012,
        0.25260806],
       [0.18400464, 0.16964791, 0.40690781, ..., 0.0598569 , 0.26322688,
        0.09320293],
       [0.85343197, 0.26462755, 0.53313173, ..., 0.9213909 , 0.27441114,
        0.7505797 ],
       ...,
       [0.68994289, 0.52642113, 0.55131234, ..., 0.45011344, 0.45500022,
        0.1421986 ],
       [0.7460126 , 0.73685755, 0.85970415, ..., 0.98114755, 0.4978151 ,
        0.98041243],
       [0.12032647, 0.95994615, 0.49725552, ..., 0.00950542, 0.99706498,
        0.51378103]])

In [3]:
int_mat = zb.integrated_series(mat)
print(int_mat)

[[ 3.14419665e-01 -1.38465964e-01  2.20955822e-01 ... -2.56350296e-01
   2.90691897e-01 -2.48444463e-01]
 [-1.90721744e-03 -4.68860463e-01  1.30842395e-01 ... -6.94469113e-01
   5.55805551e-02 -6.56294055e-01]
 [ 3.51193230e-01 -7.04275318e-01  1.66952893e-01 ... -2.71053922e-01
  -1.68346530e-01 -4.06766879e-01]
 ...
 [ 1.34323977e-01 -6.96718889e-01 -3.62917194e-01 ...  5.29846503e-03
  -4.98203631e-01 -4.92088401e-01]
 [ 3.80005054e-01 -4.59903742e-01 -2.34280623e-04 ...  4.88470298e-01
  -4.98726758e-01 -1.27285013e-02]
 [ 2.00014449e-11 -1.97941663e-12 -4.28690416e-12 ... -2.14430695e-11
  -4.14190904e-12 -3.67261777e-13]]


In [4]:
tws = zb.time_windows(4, 200)
tws

array([  4,   5,   7,   9,  11,  13,  16,  20,  24,  28,  33,  38,  45,
        52,  60,  69,  80,  91, 104, 119, 135, 154, 174, 198, 200])

In [5]:
F_DFA, DCCA, P_DCCA, DMCx2= zb.dmcx2(int_mat, tws, dmcx2_of='all-full')

In [6]:
F_DFA

array([[0.15208778, 0.15300569, 0.15291329, 0.15276036, 0.15172669,
        0.1522108 , 0.15294232, 0.15250692],
       [0.17109066, 0.17235692, 0.17219481, 0.17228324, 0.17087023,
        0.17152645, 0.17261986, 0.1720637 ],
       [0.20288299, 0.20440637, 0.20400071, 0.20453363, 0.2026289 ,
        0.20331246, 0.20501288, 0.20428874],
       [0.22989314, 0.2310388 , 0.23077463, 0.23171073, 0.22925211,
        0.22988813, 0.23226641, 0.2310873 ],
       [0.25371742, 0.25413182, 0.25439388, 0.25579224, 0.25278643,
        0.2535156 , 0.25640914, 0.25462451],
       [0.27536351, 0.27481163, 0.27575595, 0.27769813, 0.27418113,
        0.27518691, 0.27833578, 0.27587479],
       [0.30484609, 0.30286727, 0.30484714, 0.30745494, 0.30359321,
        0.30495231, 0.30835991, 0.30458514],
       [0.33983243, 0.33638317, 0.33982753, 0.34255881, 0.33947829,
        0.34069309, 0.34435243, 0.33894134],
       [0.37108625, 0.36700164, 0.37132123, 0.37395951, 0.37287395,
        0.37297313, 0.376962

In [7]:
print(DCCA)

[[-1.45802331e-04  1.17397500e-04 -5.12422053e-05  2.38166329e-05
  -3.08634809e-05  5.03209682e-06  2.02829965e-04  1.90234038e-04
  -2.26130748e-04 -5.95019250e-05 -7.39190263e-05 -4.75002989e-05
  -3.98314355e-04  2.12467352e-04 -5.03398140e-05  1.61299500e-04
   4.41575375e-05 -2.44524990e-04  2.22738948e-04 -3.03584144e-04
   1.23748165e-04 -3.41639094e-05 -5.36819662e-04  1.36324795e-04
   9.06165161e-06 -2.82715648e-04 -2.64626539e-04 -1.61600091e-04]
 [-1.87322199e-04  1.86396919e-04 -6.94199751e-05  3.28942828e-06
   6.85485262e-06  3.06948421e-05  2.08210336e-04  1.90952705e-04
  -3.52098375e-04 -7.73512743e-05 -1.50265716e-04 -1.39013188e-04
  -5.83386398e-04  2.26123384e-04 -8.81665305e-05  2.14475067e-04
  -4.58093362e-05 -2.36578171e-04  1.96028478e-04 -4.00970576e-04
   1.32911291e-04  2.05213219e-05 -5.40872281e-04  2.10565396e-04
   2.26960146e-05 -3.22240559e-04 -3.71877998e-04 -1.74777364e-04]
 [-8.21774242e-05  4.02051219e-04 -7.34237895e-05 -5.56842427e-05
  -2.764

In [8]:
P_DCCA

array([[[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00, ...,
          1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
        [-6.26559867e-03, -6.35234712e-03, -1.98158383e-03, ...,
          3.09976719e-02,  3.28017515e-02,  3.30652296e-02],
        [ 5.04799936e-03,  6.32692020e-03,  9.71413339e-03, ...,
          8.90814653e-05, -1.86730875e-03, -2.02498107e-03],
        ...,
        [-1.33323012e-03,  2.33582716e-04, -6.70299213e-04, ...,
         -2.33944493e-02, -1.13090450e-02, -1.05053974e-02],
        [ 2.16335097e-04,  1.03931775e-03,  5.07046161e-03, ...,
          2.51728607e-02,  2.65072744e-02,  2.66251638e-02],
        [ 8.74476691e-03,  7.07272429e-03,  2.98951539e-03, ...,
         -1.97772468e-02, -1.96320879e-02, -1.95752559e-02]],

       [[-6.26559867e-03, -6.35234712e-03, -1.98158383e-03, ...,
          3.09976719e-02,  3.28017515e-02,  3.30652296e-02],
        [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00, ...,
          1.00000000e+00,  1.00000000e

In [9]:
DMCx2.max(), DMCx2.min(), DMCx2

(np.float64(0.01872299916283646),
 np.float64(0.00013727479579686395),
 array([[0.00014894, 0.00051191, 0.00047088, 0.00026261, 0.00034056,
         0.0006561 , 0.00104215, 0.0006695 ],
        [0.00013727, 0.00066742, 0.00045235, 0.00024744, 0.00026788,
         0.00069561, 0.00087899, 0.00044481],
        [0.00013952, 0.00069009, 0.00049256, 0.00027341, 0.00027871,
         0.00065615, 0.0007111 , 0.00020598],
        [0.00027785, 0.00063135, 0.00064753, 0.00032707, 0.00039835,
         0.0005528 , 0.00079833, 0.00025854],
        [0.00050023, 0.00065229, 0.00079724, 0.00044341, 0.00052582,
         0.00052491, 0.00100778, 0.00041912],
        [0.00075363, 0.00077129, 0.00099395, 0.00065831, 0.00062048,
         0.00062494, 0.00129425, 0.00057275],
        [0.0010763 , 0.00108134, 0.0013206 , 0.00124734, 0.00067763,
         0.00094681, 0.00171079, 0.00074077],
        [0.0014404 , 0.00149158, 0.00166708, 0.00232496, 0.00074294,
         0.00155872, 0.00203081, 0.00092578],
        [