In [1]:
import numpy as np
import pandas as pd
import zebende as zb

In [8]:
zb.time_windows(4,3000).shape

(49,)

In [7]:
np.array([ 4, 10 ,20, 30, 40, 50, 100, 500, 1000, 3000])

array([   4,   10,   20,   30,   40,   50,  100,  300, 1000, 3000])

In [2]:
data_1 = pd.read_csv('./test_data/data_pre_proc/S001/S001_03/S001_03_F3.txt', header=None)
data_2 = pd.read_csv('./test_data/data_pre_proc/S001/S001_03/S001_03_F6.txt', header=None)
data_3 = pd.read_csv('./test_data/data_pre_proc/S001/S001_03/S001_03_P3.txt', header=None)
data_4 = pd.read_csv('./test_data/data_pre_proc/S001/S001_03/S001_03_P6.txt', header=None)
data = pd.concat([data_1, data_2, data_3, data_4], axis=1).to_numpy(dtype=np.float64)
data

array([[-28., -57., -43., -52.],
       [-32., -67., -67., -60.],
       [-44., -74., -74., -66.],
       ...,
       [-15., -54., -59., -57.],
       [  0., -41., -25., -47.],
       [-15., -48., -50., -72.]])

In [3]:
int_data = zb.integrated_series(data)

In [4]:
tws = zb.time_windows(4, int(data.shape[0]/4), exp_fac=4)
tws.size

29

In [5]:
dfa, dcca, pdcca = zb.p_dcca(int_data, tws[:5])

In [6]:
dfa

array([[10.21772684,  9.6465587 , 11.1907025 ,  9.96204291],
       [13.54907402, 12.58526165, 14.79349141, 12.92467481],
       [24.351747  , 22.04610564, 26.3471192 , 22.37345791],
       [35.91221786, 32.38197129, 38.07809875, 31.95381504],
       [52.2533971 , 47.43097228, 53.38130451, 44.48437417]])

In [7]:
dcca

array([[  84.84742407,   68.48779515,   50.78041937,   50.7699085 ,
          44.02365612,   81.59505528],
       [ 148.29977174,  120.31389053,   87.84420055,   87.81716852,
          74.88343072,  139.31154967],
       [ 477.11798398,  394.91777914,  285.80738956,  282.95188183,
         236.85826472,  437.75547984],
       [1044.62835821,  859.80326718,  629.76985533,  611.52218872,
         515.01571732,  930.38154034],
       [2240.31482874, 1791.79333467, 1345.28955774, 1270.68462293,
        1095.1818025 , 1879.59462975]])

In [8]:
pdcca

array([[0.86081923, 0.59896514, 0.49887712, 0.47030178, 0.45810527,
        0.73191068],
       [0.86969829, 0.60025456, 0.50163041, 0.47167895, 0.46036665,
        0.72861283],
       [0.8887176 , 0.61552178, 0.52457818, 0.48713302, 0.48020154,
        0.74261778],
       [0.89828945, 0.62875523, 0.54880357, 0.49594519, 0.49773076,
        0.76465074],
       [0.9039252 , 0.64236845, 0.57875367, 0.5018646 , 0.51905898,
        0.79153027]])

In [9]:
dfa_2, dcca_2, pdcca_2, dmc = zb.dmcx2(int_data, tws[:5])

[[1.         0.47030178 0.45810527]
 [0.47030178 1.         0.73191068]
 [0.45810527 0.73191068 1.        ]] [[0.86081923]
 [0.59896514]
 [0.49887712]]
[[1.         0.73191068 0.59896514]
 [0.73191068 1.         0.49887712]
 [0.59896514 0.49887712 1.        ]] [[0.47030178]
 [0.45810527]
 [0.86081923]]
[[1.         0.86081923 0.59896514]
 [0.86081923 1.         0.47030178]
 [0.59896514 0.47030178 1.        ]] [[0.49887712]
 [0.45810527]
 [0.73191068]]
[[1.         0.49887712 0.45810527]
 [0.49887712 1.         0.86081923]
 [0.45810527 0.86081923 1.        ]] [[0.73191068]
 [0.59896514]
 [0.47030178]]
[[1.         0.47167895 0.46036665]
 [0.47167895 1.         0.72861283]
 [0.46036665 0.72861283 1.        ]] [[0.86969829]
 [0.60025456]
 [0.50163041]]
[[1.         0.72861283 0.60025456]
 [0.72861283 1.         0.50163041]
 [0.60025456 0.50163041 1.        ]] [[0.47167895]
 [0.46036665]
 [0.86969829]]
[[1.         0.86969829 0.60025456]
 [0.86969829 1.         0.47167895]
 [0.60025456 0.4

In [10]:
pdcca_2.transpose(2,0,1)

array([[[1.        , 0.86081923, 0.59896514, 0.49887712],
        [0.86081923, 1.        , 0.47030178, 0.45810527],
        [0.59896514, 0.47030178, 1.        , 0.73191068],
        [0.49887712, 0.45810527, 0.73191068, 1.        ]],

       [[1.        , 0.86969829, 0.60025456, 0.50163041],
        [0.86969829, 1.        , 0.47167895, 0.46036665],
        [0.60025456, 0.47167895, 1.        , 0.72861283],
        [0.50163041, 0.46036665, 0.72861283, 1.        ]],

       [[1.        , 0.8887176 , 0.61552178, 0.52457818],
        [0.8887176 , 1.        , 0.48713302, 0.48020154],
        [0.61552178, 0.48713302, 1.        , 0.74261778],
        [0.52457818, 0.48020154, 0.74261778, 1.        ]],

       [[1.        , 0.89828945, 0.62875523, 0.54880357],
        [0.89828945, 1.        , 0.49594519, 0.49773076],
        [0.62875523, 0.49594519, 1.        , 0.76465074],
        [0.54880357, 0.49773076, 0.76465074, 1.        ]],

       [[1.        , 0.9039252 , 0.64236845, 0.57875367],
      

In [11]:
arr = np.array([[1,2,3,4], [2,3,4,5]]);arr 

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])