In [9]:
import numpy as np
#import pandas as pd
import zebende as zb


ModuleNotFoundError: No module named 'zebende'

In [2]:
mat = np.random.random(size=(800,8))
mat

array([[0.78162603, 0.39206695, 0.66237681, ..., 0.40604249, 0.39905092,
        0.68945943],
       [0.97952412, 0.07082185, 0.64770927, ..., 0.02263646, 0.85048627,
        0.69078723],
       [0.80208057, 0.57546061, 0.45096392, ..., 0.69204154, 0.64708035,
        0.79001983],
       ...,
       [0.51929152, 0.17849124, 0.07033427, ..., 0.19147607, 0.41545135,
        0.08412269],
       [0.99742101, 0.94332501, 0.70316704, ..., 0.05773092, 0.31297315,
        0.37871364],
       [0.50902453, 0.73403744, 0.34284205, ..., 0.20083544, 0.2852562 ,
        0.38508756]])

In [5]:
int_mat = zb.integrated_series(mat)
print(int_mat)

[[ 2.87443867e-01 -1.07017224e-01  1.55674377e-01 ... -8.94382395e-02
  -9.64381896e-02  2.04422610e-01]
 [ 7.72785821e-01 -5.35279555e-01  2.96681216e-01 ... -5.62282505e-01
   2.58558967e-01  4.10173029e-01]
 [ 1.08068423e+00 -4.58903116e-01  2.40942704e-01 ... -3.65721697e-01
   4.10150211e-01  7.15156040e-01]
 ...
 [-5.18081214e-01 -6.79194096e-01 -3.26042210e-02 ...  7.32395097e-01
   3.92748869e-01  2.06272427e-01]
 [-1.48423674e-02 -2.34953267e-01  1.63860386e-01 ...  2.94645288e-01
   2.10232906e-01  9.99492518e-02]
 [-6.44539977e-13  3.82804899e-13  2.99760217e-15 ...  8.88178420e-15
  -2.63677968e-13 -2.36255460e-13]]


In [3]:
tws = zb.time_windows(4, 200)
tws

array([  4,   5,   7,   9,  11,  13,  16,  20,  24,  28,  33,  38,  45,
        52,  60,  69,  80,  91, 104, 119, 135, 154, 174, 198, 200])

In [6]:
F_DFA, DCCA, P_DCCA = zb.p_dcca(int_mat, tws)

In [7]:
F_DFA

array([[0.15099014, 0.15240823, 0.14734952, 0.15416691, 0.15588797,
        0.15152661, 0.15627751, 0.15315372],
       [0.17001305, 0.17075328, 0.1651528 , 0.17486803, 0.17602541,
        0.17046717, 0.17548571, 0.17217862],
       [0.20244264, 0.2001879 , 0.19274464, 0.2086493 , 0.20795969,
        0.20319183, 0.20789024, 0.20259898],
       [0.23167838, 0.22396312, 0.21536783, 0.23808471, 0.23379289,
        0.23105802, 0.23460383, 0.2284017 ],
       [0.25825333, 0.2448937 , 0.23627889, 0.2637922 , 0.25687767,
        0.25452585, 0.25944782, 0.25185792],
       [0.28160099, 0.26425179, 0.254741  , 0.28571798, 0.27831518,
        0.27454178, 0.28255564, 0.27347573],
       [0.3108282 , 0.28986588, 0.2794402 , 0.31410936, 0.30783666,
        0.3017377 , 0.31297419, 0.30264153],
       [0.34339648, 0.3208568 , 0.30998115, 0.34645146, 0.34544526,
        0.33732073, 0.34741158, 0.33686697],
       [0.37209278, 0.34989471, 0.33811421, 0.37479564, 0.38156284,
        0.37016441, 0.378371

In [11]:
print(DCCA)

[[ 9.06690042e-04 -7.34385149e-04  1.11755513e-03  1.93091944e-03
  -1.03190958e-03  7.61598468e-04  9.51373383e-04 -1.31762986e-03
   1.61905748e-03  6.45708645e-04 -4.20916253e-04  1.53742115e-03
   1.53022974e-03  1.31806565e-03 -8.95467799e-04 -1.53425456e-03
  -6.98976298e-04 -4.11295210e-04 -1.88833201e-03 -4.43184096e-05
  -4.92431566e-04  7.48151981e-04 -8.93829719e-04  7.47292611e-04
   9.00073921e-04 -4.21959638e-04  1.08360206e-03  5.16306302e-04]
 [ 1.43024317e-03 -5.89019826e-04  1.21319361e-03  2.57409324e-03
  -1.08174575e-03  7.32223060e-04  1.34881061e-03 -1.87048945e-03
   2.14520356e-03  1.03953097e-03 -7.62164643e-04  2.17301170e-03
   2.23544906e-03  1.40238759e-03 -1.03225131e-03 -2.21703731e-03
  -1.08081876e-03 -7.95966376e-04 -2.41651557e-03  1.72545202e-04
  -6.22648216e-04  1.07122775e-03 -1.44186602e-03  1.02197456e-03
   1.16298689e-03 -5.88207922e-04  1.20748358e-03  9.81872891e-04]
 [ 2.78794880e-03 -3.44867308e-04  8.58553438e-04  3.75146505e-03
  -1.107

In [9]:
P_DCCA

array([[ 3.9400e-02, -3.3010e-02,  4.8010e-02,  8.2040e-02, -4.5100e-02,
         3.2280e-02,  4.1140e-02, -5.8670e-02,  6.8910e-02,  2.7180e-02,
        -1.8230e-02,  6.4550e-02,  6.5560e-02,  5.8020e-02, -3.8980e-02,
        -6.8720e-02, -3.0350e-02, -1.8230e-02, -7.8570e-02, -1.9000e-03,
        -2.0440e-02,  3.1690e-02, -3.7840e-02,  3.0670e-02,  3.7700e-02,
        -1.7820e-02,  4.6690e-02,  2.1570e-02],
       [ 4.9270e-02, -2.0980e-02,  4.0810e-02,  8.6010e-02, -3.7330e-02,
         2.4540e-02,  4.6080e-02, -6.6330e-02,  7.1840e-02,  3.4590e-02,
        -2.6180e-02,  7.2520e-02,  7.6040e-02,  4.8560e-02, -3.5510e-02,
        -7.8750e-02, -3.7290e-02, -2.7990e-02, -7.8510e-02,  5.7900e-03,
        -2.0290e-02,  3.5580e-02, -4.8050e-02,  3.3080e-02,  3.8370e-02,
        -1.9660e-02,  4.1140e-02,  3.2500e-02],
       [ 6.8790e-02, -8.8400e-03,  2.0330e-02,  8.9110e-02, -2.6920e-02,
         2.9160e-02,  4.9790e-02, -8.7660e-02,  5.5270e-02,  5.1670e-02,
        -3.9830e-02,  7.2320