In [2]:
import numpy as np
import zebende as zb
import pandas as pd

In [5]:
np.geomspace(4, 1048575/4, 10, dtype=int)

array([     4,     13,     47,    161,    552,   1896,   6501,  22295,
        76449, 262143])

In [6]:
zb.time_windows(4, int(1048575/4), exp_fac=2)

array([     4,      7,     12,     19,     32,     50,     80,    124,
          192,    294,    448,    678,   1024,   1538,   2304,   3439,
         5120,   7602,  11264,  16653,  24576,  36203,  53248,  78200,
       114688, 167985, 245760, 262143])

In [12]:
tws = pd.read_csv('./test_data/fof_data/dfa_C1.dat',sep = ' ', header=None).iloc[:,0].to_numpy()
tws[:5]

array([ 4,  5,  7,  9, 11])

In [8]:
data_1 = pd.read_csv('./test_data/fof_data/C1.txt', header=None)
data_2 = pd.read_csv('./test_data/fof_data/C2.txt', header=None)

data_1.shape, data_2.shape


((1048575, 1), (1048575, 1))

In [9]:
data = pd.concat([data_1, data_2], axis=1).to_numpy(dtype=np.float64)
data

array([[  1.875, -10.   ],
       [ -0.375, -12.5  ],
       [ -3.25 , -12.5  ],
       ...,
       [ 19.   ,  10.875],
       [ 23.   ,   6.875],
       [ 19.375,   6.   ]])

In [10]:
int_data = zb.integrated_series(data)
int_data

array([[-2.86619591e+00, -1.47266615e+01],
       [-7.98239182e+00, -3.19533231e+01],
       [-1.59735877e+01, -4.91799846e+01],
       ...,
       [-3.28926222e+01, -3.42168579e+00],
       [-1.46338181e+01, -1.27334733e+00],
       [-1.40256088e-05, -8.87508887e-06]])

In [13]:
dfa , dcca, pdcca = zb.p_dcca(int_data, tws[:3])

In [9]:
dfa

array([[ 4.21736741,  4.37054342],
       [ 5.33765957,  5.40752423],
       [ 7.29990383,  7.2353615 ],
       [ 8.97678766,  8.8500263 ],
       [10.45112702, 10.29925774],
       [11.79058833, 11.60589967],
       [13.66662798, 13.36234174],
       [16.11272024, 15.44218817],
       [18.01614305, 16.87010021],
       [21.49144328, 19.11780606]])

In [11]:
np.concat((tws.reshape(10,1), dfa), axis=1)

array([[ 4.        ,  4.21736741,  4.37054342],
       [ 5.        ,  5.33765957,  5.40752423],
       [ 7.        ,  7.29990383,  7.2353615 ],
       [ 9.        ,  8.97678766,  8.8500263 ],
       [11.        , 10.45112702, 10.29925774],
       [13.        , 11.79058833, 11.60589967],
       [16.        , 13.66662798, 13.36234174],
       [20.        , 16.11272024, 15.44218817],
       [23.        , 18.01614305, 16.87010021],
       [28.        , 21.49144328, 19.11780606]])

In [ ]:
dfa_2 , dcca_2, pdcca_2, dmc = zb.dmcx2(int_data, tws, dmcx2_of='all-full')

In [ ]:
dfa_2

In [ ]:
pdcca

In [ ]:
pdcca_2.shape

In [ ]:
pdcca_2.transpose(2,0,1)

In [ ]:
dmc

In [ ]:
rnd = 4
result_check = pd.read_csv('test_data/data_proc/S001/S001_03/S001_03_DMCX2_F3_F6_P3_P6.txt',sep=' ', header=None,index_col=0, dtype=np.float64).head(dmc[:,0].size).to_numpy().flatten().round(rnd)
result_check, result_check == dmc[:,0].round(rnd )

In [ ]:
if (result_check == dmc[:,0].round(rnd)).all() == True:
    print('pass')
else:
    print('found diference')


In [ ]:
dmc