In [13]:
import numpy as np
#import pandas as pd
try:
    from zebende import zebende as zb
except:
    from importlib.machinery import SourceFileLoader
    zb = SourceFileLoader("zebende", ".././zebende/__init__.py").load_module()


In [2]:
mat = np.random.random(size=(2_000,8))
mat

array([[0.57332397, 0.91835311, 0.19225866, ..., 0.76394114, 0.42679505,
        0.95754748],
       [0.35430103, 0.56802698, 0.61206676, ..., 0.12895567, 0.41582453,
        0.9877828 ],
       [0.62690687, 0.09670496, 0.47712077, ..., 0.49849816, 0.91010257,
        0.62873965],
       ...,
       [0.25149642, 0.27616728, 0.4067222 , ..., 0.11131326, 0.147793  ,
        0.45270523],
       [0.6503497 , 0.11381042, 0.58690409, ..., 0.39446848, 0.50354573,
        0.66537994],
       [0.6748158 , 0.06688302, 0.40942599, ..., 0.21828987, 0.25164316,
        0.19550145]])

In [3]:
int_mat = zb.integrated_series(mat)
print(int_mat)

[[ 7.38085157e-02  4.18501930e-01 -3.07410595e-01 ...  2.63573050e-01
  -7.24026219e-02  4.57949835e-01]
 [-7.14059099e-02  4.86677736e-01 -1.95013087e-01 ... -1.07839380e-01
  -1.55775759e-01  9.46134989e-01]
 [ 5.59855119e-02  8.35315210e-02 -2.17561572e-01 ... -1.09709314e-01
   2.55129141e-01  1.07527700e+00]
 ...
 [-3.26134588e-01  8.19008924e-01  3.00843187e-03 ...  3.87977834e-01
   2.43206449e-01  1.38313909e-01]
 [-1.75300340e-01  4.32968162e-01  9.02432688e-02 ...  2.82078219e-01
   2.47554505e-01  3.04096199e-01]
 [ 2.82552570e-09  1.53165691e-09  2.24926855e-10 ... -2.06519024e-09
  -2.32806729e-09 -3.11385695e-10]]


In [4]:
tws = zb.time_windows(4, 200)
tws

array([  4,   5,   7,   9,  11,  13,  16,  20,  24,  28,  33,  38,  45,
        52,  60,  69,  80,  91, 104, 119, 135, 154, 174, 198, 200])

In [5]:
F_DFA, DCCA, P_DCCA, DMCx2= zb.dmcx2(int_mat, tws, dmcx2_of='all-full')

In [6]:
F_DFA

array([[0.15283657, 0.15290277, 0.15259238, 0.15268856, 0.15294248,
        0.15238268, 0.1525234 , 0.15268064],
       [0.17220835, 0.17224112, 0.17194997, 0.17193929, 0.17233949,
        0.17171015, 0.17193945, 0.17192274],
       [0.2042262 , 0.20406564, 0.20403198, 0.20365624, 0.20439075,
        0.20360556, 0.20401946, 0.20362618],
       [0.23109784, 0.23073456, 0.2310987 , 0.23019336, 0.23133911,
        0.23032404, 0.23097631, 0.2300972 ],
       [0.25478964, 0.25426991, 0.25497374, 0.25355587, 0.25513962,
        0.25388289, 0.25477581, 0.25339385],
       [0.27620695, 0.27561471, 0.27658358, 0.27465199, 0.2767103 ,
        0.27522309, 0.27636504, 0.27452852],
       [0.30516602, 0.30461071, 0.3059777 , 0.30327747, 0.30608655,
        0.30409538, 0.30578158, 0.30328014],
       [0.33960055, 0.33921371, 0.34116536, 0.33751929, 0.34124692,
        0.33837032, 0.34109323, 0.33773014],
       [0.37065161, 0.37051044, 0.3729583 , 0.36870855, 0.37306759,
        0.3693363 , 0.373071

In [7]:
print(DCCA)

[[ 5.82589239e-05  1.97004515e-06 -1.32965796e-06 -8.95511532e-05
   5.30593753e-05 -5.74660156e-05  3.22415403e-05 -2.97677005e-05
   1.12206803e-04  3.04893965e-05  1.50499045e-05 -7.44856293e-05
  -1.44989256e-05 -1.16444649e-05  4.79962754e-06  4.70656477e-05
  -2.23096105e-05 -7.06831941e-05  1.10240279e-04  1.16274913e-04
   3.25923357e-05 -2.87914950e-05  2.77293509e-05 -3.80089552e-05
  -5.11239513e-05  9.82557286e-05 -6.53390191e-05  1.12656042e-04]
 [ 7.80483319e-05  2.27527590e-05 -1.04654373e-05 -1.15844542e-04
   8.84485353e-05 -8.48710765e-05  3.17490498e-05 -4.67937717e-05
   1.53338327e-04  3.53681798e-05  9.94986571e-06 -7.34380892e-05
  -8.67166078e-06 -2.07851430e-05  3.78617297e-05  6.59357669e-05
  -4.89140935e-05 -8.70762506e-05  1.35988952e-04  1.24426520e-04
   4.04140756e-05 -2.92241660e-05  4.55266158e-05 -5.77526216e-05
  -6.81268709e-05  8.34620049e-05 -7.48138946e-05  1.34308142e-04]
 [ 1.43698664e-04  6.84297268e-05 -4.89308811e-05 -1.94678966e-04
   1.570

In [8]:
P_DCCA

array([[[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00, ...,
          1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
        [ 2.49298593e-03,  2.63131347e-03,  3.44803270e-03, ...,
          1.31883841e-02,  1.40843580e-02,  1.41370912e-02],
        [ 8.44726365e-05,  7.68383030e-04,  1.64223424e-03, ...,
         -8.50689856e-03, -4.14979455e-03, -3.77125993e-03],
        ...,
        [ 2.27823890e-03,  2.99116578e-03,  3.77636232e-03, ...,
         -6.58225980e-03, -7.96718857e-03, -8.10121000e-03],
        [-2.46517264e-03, -2.86635504e-03, -3.08540321e-03, ...,
         -2.29307078e-03, -2.38146716e-03, -2.41047422e-03],
        [ 1.38167070e-03,  1.07236638e-03,  7.42610501e-04, ...,
         -1.17168181e-02, -1.14262947e-02, -1.13691687e-02]],

       [[ 2.49298593e-03,  2.63131347e-03,  3.44803270e-03, ...,
          1.31883841e-02,  1.40843580e-02,  1.41370912e-02],
        [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00, ...,
          1.00000000e+00,  1.00000000e

In [9]:
DMCx2.max(), DMCx2.min(), DMCx2

(np.float64(0.0018990223087635542),
 np.float64(1.6121168803572815e-05),
 array([[3.41886231e-05, 4.35639794e-05, 7.39114079e-05, 6.32545992e-05,
         1.61211688e-05, 4.90743522e-05, 6.18769423e-05, 4.74465264e-05],
        [4.13286991e-05, 4.39525647e-05, 6.89743552e-05, 5.15239217e-05,
         2.15579539e-05, 4.31514614e-05, 4.86190819e-05, 5.06931761e-05],
        [6.22375450e-05, 5.13780391e-05, 6.82928386e-05, 3.74964885e-05,
         2.96514815e-05, 3.10783212e-05, 3.74559474e-05, 6.99356888e-05],
        [8.65112399e-05, 6.00723903e-05, 6.57705761e-05, 2.50762505e-05,
         3.16191150e-05, 2.25489859e-05, 2.70956747e-05, 9.07972347e-05],
        [1.13410132e-04, 7.00925676e-05, 7.26522593e-05, 1.91034284e-05,
         3.13738314e-05, 2.29391052e-05, 2.48031469e-05, 1.08777603e-04],
        [1.42732167e-04, 7.91647463e-05, 9.00077701e-05, 1.91257855e-05,
         3.29699493e-05, 2.71146651e-05, 3.49024501e-05, 1.23154078e-04],
        [1.85058291e-04, 8.92517245e-05, 1.23