In [25]:
import numpy as np
#import pandas as pd
try:
    from zebende import zebende as zb
except:
    print('Exception')
    from importlib.machinery import SourceFileLoader
    zb = SourceFileLoader("zebende", ".././zebende/__init__.py").load_module()


Exception


In [26]:
mat = np.random.random(size=(2_000,8))
mat

array([[0.20261335, 0.30238794, 0.77136217, ..., 0.25666849, 0.79527833,
        0.24710851],
       [0.40020833, 0.95152676, 0.73445617, ..., 0.07103245, 0.73372331,
        0.79635644],
       [0.18730032, 0.91543978, 0.26441603, ..., 0.76694911, 0.82680151,
        0.64940183],
       ...,
       [0.06793794, 0.67871333, 0.09546454, ..., 0.65266211, 0.91554096,
        0.98069062],
       [0.40758949, 0.25240763, 0.76630993, ..., 0.87906111, 0.28772955,
        0.10410905],
       [0.2591432 , 0.023595  , 0.24730166, ..., 0.44016627, 0.51425712,
        0.08840444]], shape=(2000, 8))

In [27]:
int_mat, med = zb.integrated_series(mat.T, axis = 0, return_mean = True)
assert (mat.T.shape == int_mat.shape)
print(int_mat.shape, med.shape)
print(int_mat)




(8, 2000) (8,)
[[-3.03462410e-01 -4.09329837e-01 -7.28105278e-01 ...  3.45418836e-01
   2.46932565e-01  5.04041253e-14]
 [-2.01224815e-01  2.46689191e-01  6.58516222e-01 ...  7.31222871e-01
   4.80017748e-01 -1.78668191e-12]
 [ 2.69976914e-01  5.03047826e-01  2.66078594e-01 ... -1.08410730e-02
   2.54083597e-01  1.24078525e-12]
 ...
 [-2.48753483e-01 -6.83143003e-01 -4.21615866e-01 ... -3.08383439e-01
   6.52556967e-02  3.69482223e-13]
 [ 3.02884370e-01  5.44213722e-01  8.78621275e-01 ...  1.82801250e-01
  -2.18631639e-02 -1.33504319e-12]
 [-2.57647780e-01  3.39523680e-02  1.78597913e-01 ...  8.16999085e-01
   4.16351846e-01 -1.26409994e-12]]


In [28]:
int_mat_1, med_1 = zb.integrated_series(mat, axis = 1, return_mean = True)
assert (mat.shape == int_mat_1.shape)
print(int_mat_1.shape, med_1.shape)
print(int_mat_1)

(2000, 8) (8,)
[[-3.03462410e-01 -2.01224815e-01  2.69976914e-01 ... -2.48753483e-01
   3.02884370e-01 -2.57647780e-01]
 [-4.09329837e-01  2.46689191e-01  5.03047826e-01 ... -6.83143003e-01
   5.44213722e-01  3.39523680e-02]
 [-7.28105278e-01  6.58516222e-01  2.66078594e-01 ... -4.21615866e-01
   8.78621275e-01  1.78597913e-01]
 ...
 [ 3.45418836e-01  7.31222871e-01 -1.08410730e-02 ... -3.08383439e-01
   1.82801250e-01  8.16999085e-01]
 [ 2.46932565e-01  4.80017748e-01  2.54083597e-01 ...  6.52556967e-02
  -2.18631639e-02  4.16351846e-01]
 [ 5.04041253e-14 -1.78668191e-12  1.24078525e-12 ...  3.69482223e-13
  -1.33504319e-12 -1.26409994e-12]]


In [29]:
assert (int_mat_1.T == int_mat).all()
assert (med == med_1).all()

In [30]:
tws = zb.time_windows(4, 200)
tws

array([  4,   5,   7,   9,  11,  13,  16,  20,  24,  28,  33,  38,  45,
        52,  60,  69,  80,  91, 104, 119, 135, 154, 174, 198, 200])

In [31]:
F_DFA, DCCA, P_DCCA, DMCx2= zb.dmcx2(int_mat, tws, dmcx2_of='all-full' )

In [32]:
F_DFA_1, DCCA_1, P_DCCA_1, DMCx2_1= zb.dmcx2(int_mat_1, tws, dmcx2_of='all-full', axis=1 )

In [33]:
assert (F_DFA == F_DFA_1).all()
assert (DCCA == DCCA_1).all()
assert (P_DCCA == P_DCCA_1).all()
assert (DMCx2 == DMCx2_1).all()

In [34]:
F_DFA

array([[0.15062638, 0.1520503 , 0.15428342, 0.156855  , 0.1517338 ,
        0.15327067, 0.15195542, 0.15175438],
       [0.16976145, 0.17202288, 0.1730585 , 0.17668221, 0.17205984,
        0.17345254, 0.17158841, 0.17056329],
       [0.20188968, 0.20552341, 0.20447559, 0.20859589, 0.2057934 ,
        0.20647688, 0.20488425, 0.2021783 ],
       [0.22947339, 0.23312573, 0.23081931, 0.23455523, 0.23321213,
        0.23378516, 0.23262109, 0.22834061],
       [0.25453931, 0.2569508 , 0.25392435, 0.25708137, 0.25706149,
        0.25804745, 0.25667215, 0.25069358],
       [0.27784704, 0.27829645, 0.27413722, 0.27685064, 0.2782489 ,
        0.28063603, 0.2778914 , 0.27125248],
       [0.3099061 , 0.3063334 , 0.30104905, 0.30304687, 0.30597708,
        0.31293173, 0.30508272, 0.30049134],
       [0.3474714 , 0.33958877, 0.33328917, 0.3341584 , 0.3372486 ,
        0.35239985, 0.33628883, 0.33786884],
       [0.38045087, 0.37044773, 0.36293995, 0.36211491, 0.36389912,
        0.38682207, 0.365035

In [35]:
print(DCCA)

[[-1.16536688e-04 -6.23619795e-04  2.87215284e-04 -7.07209059e-04
   4.06212450e-04  6.46785604e-04  6.57407389e-04 -1.74495054e-04
  -4.56604853e-04 -4.02917429e-04 -8.30286399e-04 -1.83723254e-04
   4.17344246e-04 -7.15191014e-04 -9.24346700e-05 -9.31736864e-04
   8.15245894e-04  1.47902920e-04  5.21805929e-04 -7.31883708e-04
  -3.64632350e-04  4.71794218e-05  4.98091790e-04  1.31428079e-03
  -9.65561148e-04 -2.79806706e-05 -1.94104296e-04  4.15297213e-04]
 [ 2.14930495e-05 -8.08631648e-04  4.95318366e-04 -1.08388885e-03
   4.89048936e-04  7.50916923e-04  6.71355485e-04 -2.37725225e-04
  -3.61777681e-04 -6.48415965e-04 -9.79710036e-04  4.88954505e-06
   5.06797700e-04 -8.27254396e-04  1.77518479e-04 -8.47907086e-04
   1.27695407e-03  3.60398611e-05  3.47520535e-04 -8.41901744e-04
  -7.54939946e-04 -5.89727323e-05  6.93471717e-04  1.97754505e-03
  -1.28232933e-03 -1.88966789e-04 -3.97212022e-04  3.28242497e-04]
 [ 5.12563865e-04 -8.25233634e-04  6.80333398e-04 -2.08308264e-03
   4.584

In [36]:
P_DCCA

array([[[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00, ...,
          1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
        [-5.08831946e-03,  7.35991421e-04,  1.23530037e-02, ...,
         -6.63247154e-02, -4.82304693e-02, -4.63633142e-02],
        [-2.68348777e-02, -2.75244557e-02, -1.99903930e-02, ...,
          1.37267128e-01,  1.48499484e-01,  1.49504015e-01],
        ...,
        [ 1.75951569e-02,  1.66085836e-02,  1.09969939e-02, ...,
          4.04225782e-02,  3.39678730e-02,  3.35497398e-02],
        [ 2.82581113e-02,  2.57789287e-02,  2.48517503e-02, ...,
         -1.15390345e-01, -1.67139205e-01, -1.71721722e-01],
        [ 2.87602269e-02,  2.31861117e-02,  1.48208767e-02, ...,
         -1.70182890e-02, -2.55626167e-02, -2.65504540e-02]],

       [[-5.08831946e-03,  7.35991421e-04,  1.23530037e-02, ...,
         -6.63247154e-02, -4.82304693e-02, -4.63633142e-02],
        [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00, ...,
          1.00000000e+00,  1.00000000e

In [37]:
DMCx2.max(), DMCx2.min(), DMCx2

(np.float64(0.13436563409276603),
 np.float64(0.001765812837475892),
 array([[0.00387871, 0.00241227, 0.00454147, 0.00321136, 0.00738052,
         0.00469896, 0.00611986, 0.003309  ],
        [0.00404343, 0.0020213 , 0.00421108, 0.00276386, 0.00907895,
         0.00374629, 0.00803614, 0.00297671],
        [0.00446481, 0.00201355, 0.00414091, 0.00203497, 0.01368397,
         0.00284451, 0.0108699 , 0.00426416],
        [0.00460049, 0.00238699, 0.00378743, 0.00176581, 0.01813891,
         0.00279369, 0.01148554, 0.00672806],
        [0.0041436 , 0.00279849, 0.00352141, 0.00260466, 0.02136071,
         0.00366043, 0.01144217, 0.00854059],
        [0.00338066, 0.00309129, 0.00323935, 0.00373728, 0.0235603 ,
         0.0050652 , 0.01115592, 0.0098275 ],
        [0.0028809 , 0.00401906, 0.00269808, 0.00456455, 0.02545575,
         0.00817515, 0.01053066, 0.01181939],
        [0.00420557, 0.00712183, 0.00194188, 0.00477155, 0.02693304,
         0.01283431, 0.00978559, 0.01514198],
        [0.