In [1]:
import numpy as np
#import pandas as pd
try:
    from zebende import zebende as zb
except:
    print('Exception')
    from importlib.machinery import SourceFileLoader
    zb = SourceFileLoader("zebende", ".././zebende/__init__.py").load_module()


Exception


In [2]:
mat = np.random.random(size=(2_000,8))
mat

array([[0.5134076 , 0.19882843, 0.40799853, ..., 0.31476512, 0.98892132,
        0.29347584],
       [0.77659273, 0.70190941, 0.86702308, ..., 0.86983433, 0.95365483,
        0.01010395],
       [0.57094868, 0.43226126, 0.4046239 , ..., 0.72920044, 0.76383244,
        0.30815364],
       ...,
       [0.93728249, 0.82886238, 0.63526561, ..., 0.70903051, 0.64767254,
        0.86126149],
       [0.94806594, 0.81528912, 0.71270905, ..., 0.92291571, 0.49410405,
        0.35060605],
       [0.54207032, 0.72430812, 0.5570828 , ..., 0.61224736, 0.91780718,
        0.33036499]], shape=(2000, 8))

In [3]:
int_mat, med = zb.integrated_series(mat.T, axis=0, return_mean = True)
print(int_mat.shape, med.shape)
print(int_mat)


(8, 2000) (8,)
[[ 1.03301134e-02  2.83845365e-01  3.51716565e-01 ... -4.83981293e-01
  -3.89928334e-02 -1.74416037e-13]
 [-2.99423304e-01 -9.57656223e-02 -1.61756091e-01 ... -5.43093774e-01
  -2.26056388e-01 -1.65978342e-13]
 [-8.76211972e-02  2.83782159e-01  1.92786336e-01 ... -2.78552406e-01
  -6.14630805e-02  1.13020704e-12]
 ...
 [-1.87100661e-01  1.80867886e-01  4.08202539e-01 ... -5.31431495e-01
  -1.10381573e-01 -1.50790491e-12]
 [ 4.82063254e-01  9.28860016e-01  1.18583439e+00 ... -3.98195094e-01
  -4.10949113e-01 -1.80333526e-12]
 [-2.12441625e-01 -7.08255139e-01 -9.06018964e-01 ...  3.30863888e-01
   1.75552475e-01  1.51423318e-12]]


In [4]:
int_mat_1, med_1 = zb.integrated_series(mat, axis=1, return_mean = True)
print(int_mat_1.shape, med_1.shape)
print(int_mat_1)

(2000, 8) (8,)
[[ 1.03301134e-02 -2.99423304e-01 -8.76211972e-02 ... -1.87100661e-01
   4.82063254e-01 -2.12441625e-01]
 [ 2.83845365e-01 -9.57656223e-02  2.83782159e-01 ...  1.80867886e-01
   9.28860016e-01 -7.08255139e-01]
 [ 3.51716565e-01 -1.61756091e-01  1.92786336e-01 ...  4.08202539e-01
   1.18583439e+00 -9.06018964e-01]
 ...
 [-4.83981293e-01 -5.43093774e-01 -2.78552406e-01 ... -5.31431495e-01
  -3.98195094e-01  3.30863888e-01]
 [-3.89928334e-02 -2.26056388e-01 -6.14630805e-02 ... -1.10381573e-01
  -4.10949113e-01  1.75552475e-01]
 [-1.74416037e-13 -1.65978342e-13  1.13020704e-12 ... -1.50790491e-12
  -1.80333526e-12  1.51423318e-12]]


In [5]:
(int_mat_1.T == int_mat).all()

np.True_

In [6]:
tws = zb.time_windows(4, 200)
tws

array([  4,   5,   7,   9,  11,  13,  16,  20,  24,  28,  33,  38,  45,
        52,  60,  69,  80,  91, 104, 119, 135, 154, 174, 198, 200])

In [7]:
F_DFA, DCCA, P_DCCA, DMCx2= zb.dmcx2(int_mat, tws, dmcx2_of='all-full' )

<class 'numpy.ndarray'>


In [8]:
F_DFA

array([[0.15431398, 0.15104976, 0.15184439, 0.15436768, 0.15335756,
        0.15271812, 0.15314559, 0.15226161],
       [0.17333565, 0.17009982, 0.17181031, 0.17206202, 0.17197963,
        0.17252758, 0.17207723, 0.17177241],
       [0.20519815, 0.20163256, 0.20499521, 0.20053811, 0.20189284,
        0.20527935, 0.20368612, 0.20364591],
       [0.23206364, 0.22849935, 0.23240398, 0.22433222, 0.2265047 ,
        0.23296124, 0.22940256, 0.23040274],
       [0.25563944, 0.25160148, 0.25631687, 0.24591265, 0.24810747,
        0.25719412, 0.2510721 , 0.25415505],
       [0.27718985, 0.27276553, 0.27728589, 0.26661824, 0.26853816,
        0.27838472, 0.2702991 , 0.27647008],
       [0.30623529, 0.30255198, 0.30458762, 0.2970462 , 0.29775285,
        0.30641904, 0.2960309 , 0.3076836 ],
       [0.34098368, 0.33810893, 0.33679809, 0.33624076, 0.33317046,
        0.33962621, 0.32707303, 0.34567162],
       [0.37294629, 0.36993641, 0.3648029 , 0.37235173, 0.36482236,
        0.37010449, 0.356736

In [9]:
print(DCCA)

[[ 2.78222685e-05 -1.03327851e-03  2.42591207e-05 -1.34794151e-03
  -6.83335614e-04 -1.11884701e-04  2.19607798e-04  9.28202773e-05
  -1.11233654e-03 -1.01513904e-03 -5.34570500e-04 -3.09586269e-04
  -6.71996038e-04  3.93554111e-04  2.16585473e-04  4.67773128e-04
  -3.12731083e-04  9.55261345e-04  4.80887816e-05 -3.69075947e-05
   1.37002367e-04  4.75252179e-04  1.41051506e-04  2.07073363e-04
   5.97070196e-04  4.09767696e-04  1.07580025e-03 -5.54757470e-04]
 [ 1.97621527e-04 -1.06679542e-03 -1.07186780e-06 -1.55651766e-03
  -9.17635079e-04  8.31893585e-05  2.65230776e-04 -2.64176996e-04
  -1.20977654e-03 -1.20146395e-03 -7.37802039e-04 -4.87814475e-04
  -6.90260215e-04  4.32039752e-04  1.04183908e-04  4.56582046e-04
  -2.42520935e-04  1.24174386e-03 -1.75799761e-04 -1.36060572e-04
   1.14141223e-04  8.09094491e-04  5.68343075e-04  1.23496823e-04
   7.26075838e-04  7.78841482e-04  1.40377450e-03 -5.83908720e-04]
 [ 5.47252210e-04 -9.72137526e-04 -2.56247108e-04 -1.68700293e-03
  -1.285

In [10]:
P_DCCA

array([[[ 1.        ,  1.        ,  1.        , ...,  1.        ,
          1.        ,  1.        ],
        [ 0.00119362,  0.00670259,  0.01322676, ...,  0.26213048,
          0.24230921,  0.24009993],
        [-0.04409744, -0.03582152, -0.02311057, ...,  0.21666034,
          0.2077017 ,  0.20700145],
        ...,
        [-0.02899601, -0.03068482, -0.0305117 , ..., -0.18124066,
         -0.16454858, -0.16286387],
        [-0.00473436,  0.00278905,  0.02024678, ..., -0.13234925,
         -0.11564386, -0.1142432 ],
        [ 0.00934657,  0.00890805,  0.0108746 , ...,  0.06742625,
          0.06299474,  0.06203039]],

       [[ 0.00119362,  0.00670259,  0.01322676, ...,  0.26213048,
          0.24230921,  0.24009993],
        [ 1.        ,  1.        ,  1.        , ...,  1.        ,
          1.        ,  1.        ],
        [ 0.00404691, -0.00903945, -0.02669674, ..., -0.01810238,
         -0.07471566, -0.07928089],
        ...,
        [-0.02317365, -0.02514071, -0.03210055, ..., -

In [11]:
DMCx2.max(), DMCx2.min(), DMCx2

(np.float64(0.20469880355958087),
 np.float64(0.0013926236395410585),
 array([[0.00612741, 0.005612  , 0.00447858, 0.00294552, 0.00588973,
         0.00413142, 0.00139262, 0.0062699 ],
        [0.0050458 , 0.00475949, 0.00352412, 0.00271142, 0.00528366,
         0.0049358 , 0.00150717, 0.00626776],
        [0.00384858, 0.0048292 , 0.00364992, 0.00385294, 0.00424246,
         0.00623815, 0.00229604, 0.00592049],
        [0.00360223, 0.00566149, 0.00396205, 0.00556035, 0.00429308,
         0.00734511, 0.00369184, 0.00598211],
        [0.00350408, 0.00631442, 0.00432281, 0.0075669 , 0.00466198,
         0.00808875, 0.0053017 , 0.00676338],
        [0.00345715, 0.00687614, 0.00557617, 0.01010996, 0.00543603,
         0.00858101, 0.00679211, 0.00803471],
        [0.00368154, 0.00767922, 0.00940862, 0.01496268, 0.00727618,
         0.00955514, 0.0087052 , 0.01095213],
        [0.00533121, 0.0087331 , 0.01693882, 0.02165508, 0.01026649,
         0.01145798, 0.0105392 , 0.01512362],
        [0