In [1]:
import numpy as np
#import pandas as pd
try:
    from zebende import zebende as zb
except:
    print('Exception')
    from importlib.machinery import SourceFileLoader
    zb = SourceFileLoader("zebende", ".././zebende/__init__.py").load_module()


Exception


In [2]:
mat = np.random.random(size=(2_000,8))
mat

array([[9.13698342e-01, 3.58353430e-01, 2.85244853e-02, ...,
        1.31685294e-01, 7.13942738e-01, 2.50230403e-01],
       [4.42714292e-01, 3.95203190e-01, 9.39576508e-01, ...,
        4.19116429e-01, 1.22961803e-02, 7.54467532e-01],
       [8.59858689e-01, 5.64386832e-01, 1.86503053e-02, ...,
        3.79007211e-01, 4.43012724e-01, 7.79592423e-01],
       ...,
       [4.84485188e-01, 1.78469857e-01, 8.77337782e-01, ...,
        9.32516122e-01, 2.01420538e-01, 1.94950987e-04],
       [3.28237118e-01, 1.91882363e-01, 4.38299060e-01, ...,
        5.26120385e-01, 9.43724824e-01, 3.28170455e-01],
       [6.82253853e-01, 9.39775545e-02, 8.57396973e-01, ...,
        5.73960060e-01, 3.36983443e-01, 1.60831185e-01]], shape=(2000, 8))

In [3]:
int_mat, med = zb.integrated_series(mat.T, axis=0, return_mean = True)
print(int_mat.shape, med.shape)
print(int_mat)


(8, 2000) (8,)
[[ 4.18057459e-01  3.65130868e-01  7.29348674e-01 ... -1.92092050e-02
  -1.86612970e-01  2.54041232e-12]
 [-1.35770213e-01 -2.34690665e-01 -1.64427476e-01 ...  7.02387367e-01
   4.00146088e-01  9.86544180e-13]
 [-4.73256234e-01 -3.54604446e-02 -5.18590858e-01 ... -2.92134595e-01
  -3.55616254e-01  9.54791801e-14]
 ...
 [-3.62838392e-01 -4.38245649e-01 -5.53762125e-01 ... -1.11033072e-01
  -7.94363736e-02  1.18793864e-14]
 [ 2.05753952e-01 -2.90138654e-01 -3.55314716e-01 ... -2.64330695e-01
   1.71205343e-01 -3.87245791e-13]
 [-2.50149392e-01  3.93834440e-03  2.83150972e-01 ...  5.11757951e-01
   3.39548610e-01 -4.80393503e-13]]


In [4]:
int_mat_1, med_1 = zb.integrated_series(mat, axis=1, return_mean = True)
print(int_mat_1.shape, med_1.shape)
print(int_mat_1)

(2000, 8) (8,)
[[ 4.18057459e-01 -1.35770213e-01 -4.73256234e-01 ... -3.62838392e-01
   2.05753952e-01 -2.50149392e-01]
 [ 3.65130868e-01 -2.34690665e-01 -3.54604446e-02 ... -4.38245649e-01
  -2.90138654e-01  3.93834440e-03]
 [ 7.29348674e-01 -1.64427476e-01 -5.18590858e-01 ... -5.53762125e-01
  -3.55314716e-01  2.83150972e-01]
 ...
 [-1.92092050e-02  7.02387367e-01 -2.92134595e-01 ... -1.11033072e-01
  -2.64330695e-01  5.11757951e-01]
 [-1.86612970e-01  4.00146088e-01 -3.55616254e-01 ... -7.94363736e-02
   1.71205343e-01  3.39548610e-01]
 [ 2.54041232e-12  9.86544180e-13  9.54791801e-14 ...  1.18793864e-14
  -3.87245791e-13 -4.80393503e-13]]


In [5]:
(int_mat_1.T == int_mat).all()

np.True_

In [6]:
tws = zb.time_windows(4, 200)
tws

array([  4,   5,   7,   9,  11,  13,  16,  20,  24,  28,  33,  38,  45,
        52,  60,  69,  80,  91, 104, 119, 135, 154, 174, 198, 200])

In [7]:
F_DFA, DCCA, P_DCCA, DMCx2= zb.dmcx2(int_mat, tws, dmcx2_of='all-full' )

<class 'numpy.ndarray'>


In [8]:
F_DFA

array([[0.15403425, 0.15158726, 0.15236628, 0.15014803, 0.15400572,
        0.14996787, 0.15481211, 0.15162064],
       [0.17353859, 0.17074261, 0.1701138 , 0.16952396, 0.17245175,
        0.16919463, 0.17540034, 0.17078238],
       [0.20476623, 0.20226483, 0.19980148, 0.20117589, 0.20222007,
        0.20253394, 0.20928416, 0.20200546],
       [0.22917182, 0.2281222 , 0.22503909, 0.22666354, 0.22592716,
        0.23130313, 0.23716835, 0.2288221 ],
       [0.24971643, 0.2504173 , 0.24756358, 0.24861152, 0.2459564 ,
        0.25626423, 0.26145527, 0.25338795],
       [0.2680798 , 0.27031582, 0.26825023, 0.26837544, 0.26410414,
        0.27834722, 0.28326961, 0.27592308],
       [0.29390425, 0.29744942, 0.29672205, 0.29429347, 0.28973925,
        0.30743513, 0.31312739, 0.30516114],
       [0.3265701 , 0.33027982, 0.3319082 , 0.32414988, 0.32086513,
        0.33998395, 0.34952047, 0.33876868],
       [0.3572695 , 0.3599152 , 0.36495277, 0.34961369, 0.35010922,
        0.36756865, 0.383159

In [9]:
print(DCCA)

[[-2.25652835e-04  2.57503225e-04  7.98918474e-04  2.40035109e-04
  -8.02332729e-04 -1.36258094e-03  5.79411686e-04 -7.55625552e-06
   6.86295143e-04  4.08869665e-04 -1.68253633e-04 -2.86760622e-04
  -6.71833584e-04  9.40403369e-05 -1.20229738e-04  3.26731490e-04
   4.20525467e-04 -3.07582326e-04 -4.85216031e-04 -6.02841765e-05
   9.41086212e-04  5.78175484e-04 -1.04224147e-03 -7.53118176e-04
   3.02806039e-04 -5.10733676e-04 -4.58360546e-04 -4.33562118e-04]
 [-3.57037243e-04  5.38691267e-05  9.66737035e-04  4.94893848e-04
  -1.05348237e-03 -1.51909140e-03  5.99984159e-04 -2.07458759e-04
   1.15354802e-03  4.14189863e-04 -2.93455682e-05 -4.90459238e-04
  -8.31046991e-04 -2.74269509e-06 -1.43342552e-04  1.64743743e-04
   6.29780144e-04 -2.38983918e-04 -5.86122495e-04 -2.45830713e-04
   8.74466782e-04  7.15367429e-04 -1.40621403e-03 -1.42487301e-03
   4.19388850e-04 -4.22991112e-04 -6.82506187e-04 -8.02823006e-04]
 [-5.02839681e-04 -3.39253640e-04  8.77076304e-04  4.68312322e-04
  -1.171

In [10]:
P_DCCA

array([[[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00, ...,
          1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
        [-9.66408645e-03, -1.20496805e-02, -1.21408990e-02, ...,
          6.15702261e-02,  9.97262101e-02,  1.03122920e-01],
        [ 1.09717657e-02,  1.82475405e-03, -8.29215621e-03, ...,
         -6.24201209e-04, -1.23352668e-02, -1.31582989e-02],
        ...,
        [-3.47327353e-02, -3.58793561e-02, -2.82445509e-02, ...,
         -2.22769944e-01, -2.45306949e-01, -2.47009583e-01],
        [-5.71399799e-02, -4.99065349e-02, -3.65291939e-02, ...,
          1.26593729e-01,  1.33980480e-01,  1.33997873e-01],
        [ 2.48091349e-02,  2.02442019e-02,  1.20490906e-02, ...,
         -2.64703945e-02, -3.71409253e-02, -3.83714966e-02]],

       [[-9.66408645e-03, -1.20496805e-02, -1.21408990e-02, ...,
          6.15702261e-02,  9.97262101e-02,  1.03122920e-01],
        [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00, ...,
          1.00000000e+00,  1.00000000e

In [11]:
DMCx2.max(), DMCx2.min(), DMCx2

(np.float64(0.1387283483838669),
 np.float64(0.0004657988787546816),
 array([[0.00674232, 0.00251757, 0.00088476, 0.00509868, 0.00401756,
         0.0045017 , 0.00748478, 0.00316811],
        [0.0056554 , 0.00324947, 0.00060957, 0.00484274, 0.00551225,
         0.00449176, 0.00732357, 0.0033341 ],
        [0.00301347, 0.00300172, 0.00079279, 0.0047182 , 0.00900292,
         0.00450479, 0.01027674, 0.0045494 ],
        [0.0009424 , 0.002552  , 0.00191497, 0.00376538, 0.01106143,
         0.00430238, 0.01186601, 0.00661886],
        [0.0004658 , 0.00217123, 0.00404506, 0.00362341, 0.01172783,
         0.00390779, 0.01225485, 0.00934299],
        [0.00114383, 0.00204139, 0.00725114, 0.0046481 , 0.01208981,
         0.00368904, 0.01203522, 0.01208324],
        [0.00304977, 0.00232134, 0.01232411, 0.00710251, 0.01264724,
         0.00379909, 0.01047429, 0.01440991],
        [0.00579053, 0.00413172, 0.01865805, 0.0099596 , 0.01464351,
         0.00527049, 0.00883045, 0.01497412],
        [0.