In [1]:
import numpy as np
#import pandas as pd
try:
    from zebende import zebende as zb
except:
    print('Exception')
    from importlib.machinery import SourceFileLoader
    zb = SourceFileLoader("zebende", ".././zebende/__init__.py").load_module()


Exception


In [2]:
mat = np.random.random(size=(2_000,8))
mat

array([[0.29462525, 0.63512484, 0.30886381, ..., 0.1302936 , 0.06067309,
        0.44678139],
       [0.46125815, 0.05960695, 0.68581315, ..., 0.96583614, 0.42867987,
        0.25190913],
       [0.15524103, 0.58890132, 0.7043696 , ..., 0.37738161, 0.92541225,
        0.47765146],
       ...,
       [0.65915055, 0.66148355, 0.75348309, ..., 0.96075729, 0.9332481 ,
        0.20024565],
       [0.5873344 , 0.30847437, 0.25030397, ..., 0.15772747, 0.15914639,
        0.36083058],
       [0.27783762, 0.10819592, 0.64705151, ..., 0.20588278, 0.77953864,
        0.66772681]], shape=(2000, 8))

In [3]:
int_mat, med = zb.integrated_series(mat.T, axis=0, return_mean = True)
print(int_mat.shape, med.shape)
print(int_mat)


(8, 2000) (8,)
[[-2.03561835e-01 -2.40490767e-01 -5.83436823e-01 ...  1.31202147e-01
   2.20349463e-01  3.36508599e-13]
 [ 1.32677883e-01 -3.10162123e-01 -2.23707761e-01 ...  5.88223614e-01
   3.94251032e-01 -1.10511600e-12]
 [-2.00695316e-01 -2.44412958e-02  1.70369172e-01 ...  1.21762772e-01
  -1.37492385e-01 -1.04527498e-12]
 ...
 [-3.72895355e-01  8.97518321e-02 -3.60555174e-02 ...  6.42767666e-01
   2.97306176e-01  2.22355467e-12]
 [-4.33701383e-01 -4.99395992e-01 -6.83582128e-02 ...  5.00639186e-02
  -2.85164164e-01  6.07458528e-13]
 [-5.40899258e-02 -3.03052104e-01 -3.26271958e-01 ... -2.68147701e-02
  -1.66855501e-01  1.21647137e-12]]


In [4]:
int_mat_1, med_1 = zb.integrated_series(mat, axis=1, return_mean = True)
print(int_mat_1.shape, med_1.shape)
print(int_mat_1)

(2000, 8) (8,)
[[-2.03561835e-01  1.32677883e-01 -2.00695316e-01 ... -3.72895355e-01
  -4.33701383e-01 -5.40899258e-02]
 [-2.40490767e-01 -3.10162123e-01 -2.44412958e-02 ...  8.97518321e-02
  -4.99395992e-01 -3.03052104e-01]
 [-5.83436823e-01 -2.23707761e-01  1.70369172e-01 ... -3.60555174e-02
  -6.83582128e-02 -3.26271958e-01]
 ...
 [ 1.31202147e-01  5.88223614e-01  1.21762772e-01 ...  6.42767666e-01
   5.00639186e-02 -2.68147701e-02]
 [ 2.20349463e-01  3.94251032e-01 -1.37492385e-01 ...  2.97306176e-01
  -2.85164164e-01 -1.66855501e-01]
 [ 3.36508599e-13 -1.10511600e-12 -1.04527498e-12 ...  2.22355467e-12
   6.07458528e-13  1.21647137e-12]]


In [5]:
assert (int_mat_1.T == int_mat).all()

In [6]:
assert (med == med_1).all()

In [7]:
tws = zb.time_windows(4, 200)
tws

array([  4,   5,   7,   9,  11,  13,  16,  20,  24,  28,  33,  38,  45,
        52,  60,  69,  80,  91, 104, 119, 135, 154, 174, 198, 200])

In [8]:
F_DFA, DCCA, P_DCCA, DMCx2= zb.dmcx2(int_mat, tws, dmcx2_of='all-full' )

In [9]:
F_DFA_1, DCCA_1, P_DCCA_1, DMCx2_1= zb.dmcx2(int_mat_1, tws, dmcx2_of='all-full', axis=1 )

In [10]:
F_DFA

array([[0.15401581, 0.1512815 , 0.1538473 , 0.15278527, 0.15277531,
        0.15296829, 0.14980511, 0.15405674],
       [0.17365516, 0.16969691, 0.17373865, 0.17319206, 0.17273232,
        0.17162183, 0.16870282, 0.17277399],
       [0.20659354, 0.2007635 , 0.20596917, 0.20730974, 0.20496109,
        0.20359844, 0.20044667, 0.20432563],
       [0.23436648, 0.22827027, 0.23272457, 0.23574718, 0.23153641,
        0.23079093, 0.22796794, 0.23152292],
       [0.2583671 , 0.25324431, 0.2568954 , 0.26091072, 0.25421155,
        0.25479118, 0.25283422, 0.25618105],
       [0.27947216, 0.2760032 , 0.27923154, 0.28377165, 0.27419695,
        0.27645125, 0.27591035, 0.27858695],
       [0.30785943, 0.30653729, 0.30950229, 0.31421382, 0.30115017,
        0.30686954, 0.30763433, 0.30870099],
       [0.34227503, 0.34268726, 0.34512993, 0.35032638, 0.33462971,
        0.34419823, 0.34690033, 0.34336974],
       [0.37280016, 0.37528887, 0.37677139, 0.38303193, 0.36557502,
        0.37714019, 0.383572

In [11]:
print(DCCA)

[[ 6.39851941e-04 -3.74606062e-04 -5.80344450e-04 -8.99107222e-04
  -6.97867343e-05  5.12867336e-04  8.81320692e-04 -5.79034638e-04
   4.85315791e-04  8.07225265e-04 -2.50785654e-04  5.40131584e-04
   4.19033084e-04 -1.38012219e-04 -6.15884736e-04 -5.75846223e-04
   1.80267691e-04 -1.56945215e-04  3.74759895e-04 -1.63453834e-04
   1.60966368e-03  3.06524068e-04  1.26268518e-03 -1.08771148e-03
   6.63125538e-04 -2.46595450e-04  6.59484757e-06  9.65434426e-04]
 [ 1.16892153e-03 -5.31412371e-04 -7.07254621e-04 -1.04839156e-03
   8.52303174e-05  6.64290794e-04  1.03233861e-03 -6.18015836e-04
   6.30128107e-04  9.16118616e-04 -5.22792817e-04  8.95616952e-04
   6.21152643e-04 -6.17288152e-05 -9.16455714e-04 -6.11291757e-04
   2.03049664e-04 -1.65960688e-04  9.00062879e-05 -5.89873479e-05
   2.35589029e-03  7.76749346e-04  1.60474998e-03 -1.41981799e-03
   1.03583112e-03  8.54442414e-05  2.49037607e-04  1.40902518e-03]
 [ 2.63985702e-03 -6.49114918e-04 -5.29798517e-04 -1.41558900e-03
   4.712

In [12]:
P_DCCA

array([[[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00, ...,
          1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
        [ 2.74617607e-02,  3.96664859e-02,  6.36471432e-02, ...,
          7.32111235e-02,  8.96876073e-02,  9.05930079e-02],
        [-1.58095545e-02, -1.76135757e-02, -1.52546636e-02, ...,
         -2.43380165e-02, -5.19239100e-02, -5.36569259e-02],
        ...,
        [-2.96214403e-03,  2.85978828e-03,  1.12040093e-02, ...,
          8.45469502e-02,  8.12147103e-02,  8.12523186e-02],
        [ 2.22286513e-02,  2.26750475e-02,  2.72969587e-02, ...,
          5.99803733e-02,  8.44005544e-02,  8.60114234e-02],
        [ 3.71439383e-02,  3.44077371e-02,  2.50478059e-02, ...,
          1.00544279e-01,  1.07372804e-01,  1.07879504e-01]],

       [[ 2.74617607e-02,  3.96664859e-02,  6.36471432e-02, ...,
          7.32111235e-02,  8.96876073e-02,  9.05930079e-02],
        [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00, ...,
          1.00000000e+00,  1.00000000e

In [13]:
DMCx2.max(), DMCx2.min(), DMCx2

(np.float64(0.1145479006935975),
 np.float64(0.0013011414559183523),
 array([[0.00500616, 0.0039805 , 0.00218695, 0.00653955, 0.00975252,
         0.00374034, 0.01015907, 0.0044099 ],
        [0.005476  , 0.00512439, 0.00208357, 0.00808304, 0.00994276,
         0.00379948, 0.01259298, 0.00576075],
        [0.00706382, 0.0074396 , 0.00130114, 0.0086919 , 0.01152807,
         0.0054788 , 0.01491818, 0.0073241 ],
        [0.00768161, 0.00893336, 0.00144214, 0.00794373, 0.01280966,
         0.00778732, 0.01602756, 0.00709623],
        [0.00751295, 0.0098135 , 0.00258467, 0.00785924, 0.01365368,
         0.0102185 , 0.01659091, 0.00643911],
        [0.00679531, 0.00992075, 0.0040846 , 0.00801333, 0.0141016 ,
         0.0126091 , 0.01673597, 0.00565243],
        [0.00547947, 0.00904294, 0.00626018, 0.00861299, 0.01542752,
         0.01576867, 0.01736061, 0.00475467],
        [0.00493241, 0.00925377, 0.00816353, 0.01040398, 0.01812667,
         0.01887618, 0.01975578, 0.00479056],
        [0.