In [1]:
import numpy as np
#import pandas as pd
try:
    from zebende import zebende as zb
except:
    print('Exception')
    from importlib.machinery import SourceFileLoader
    zb = SourceFileLoader("zebende", ".././zebende/__init__.py").load_module()


Exception


In [2]:
mat = np.random.random(size=(2_000,8))
mat

array([[0.54242888, 0.81906125, 0.52539654, ..., 0.7845983 , 0.23955141,
        0.46175999],
       [0.2457003 , 0.7627464 , 0.58011242, ..., 0.12139423, 0.12650354,
        0.85363875],
       [0.13436729, 0.66417827, 0.02369095, ..., 0.18976247, 0.65874242,
        0.8929538 ],
       ...,
       [0.65353731, 0.67575492, 0.31910293, ..., 0.26164883, 0.95928891,
        0.00505321],
       [0.1419156 , 0.59985374, 0.69444519, ..., 0.09764274, 0.43861766,
        0.19272415],
       [0.75361446, 0.3619571 , 0.2780977 , ..., 0.95480949, 0.67762984,
        0.05833562]], shape=(2000, 8))

In [8]:
int_mat, med = zb.integrated_series(mat.T, axis=0, return_mean = True)
print(int_mat.shape, med.shape)
print(int_mat)


(8, 2000) (8,)
[[ 4.46795144e-02 -2.07369552e-01 -5.70751632e-01 ...  9.99686815e-02
  -2.55865087e-01  1.07580611e-13]
 [ 3.22812988e-01  5.89311125e-01  7.57241127e-01 ...  3.06856937e-02
   1.34291166e-01 -1.79345427e-12]
 [ 2.07831459e-02  9.62821652e-02 -3.84640283e-01 ...  3.66839026e-02
   2.26515694e-01 -9.22151244e-13]
 ...
 [ 2.90082348e-01 -8.30393727e-02 -3.87792860e-01 ... -6.34203237e-02
  -4.60293535e-01 -6.36046771e-13]
 [-2.48810751e-01 -6.10669375e-01 -4.40289121e-01 ... -1.39523170e-01
  -1.89267671e-01 -3.24129612e-13]
 [-4.28752472e-02  3.06128265e-01  6.94446830e-01 ...  7.58210701e-01
   4.46299617e-01  1.16895382e-12]]


In [9]:
int_mat_1, med_1 = zb.integrated_series(mat, axis=1, return_mean = True)
print(int_mat_1.shape, med_1.shape)
print(int_mat_1)

(2000, 8) (8,)
[[ 4.46795144e-02  3.22812988e-01  2.07831459e-02 ...  2.90082348e-01
  -2.48810751e-01 -4.28752472e-02]
 [-2.07369552e-01  5.89311125e-01  9.62821652e-02 ... -8.30393727e-02
  -6.10669375e-01  3.06128265e-01]
 [-5.70751632e-01  7.57241127e-01 -3.84640283e-01 ... -3.87792860e-01
  -4.40289121e-01  6.94446830e-01]
 ...
 [ 9.99686815e-02  3.06856937e-02  3.66839026e-02 ... -6.34203237e-02
  -1.39523170e-01  7.58210701e-01]
 [-2.55865087e-01  1.34291166e-01  2.26515694e-01 ... -4.60293535e-01
  -1.89267671e-01  4.46299617e-01]
 [ 1.07580611e-13 -1.79345427e-12 -9.22151244e-13 ... -6.36046771e-13
  -3.24129612e-13  1.16895382e-12]]


In [6]:
(int_mat_1.T == int_mat).all()

np.True_

In [11]:
tws = zb.time_windows(4, 200)
tws

array([  4,   5,   7,   9,  11,  13,  16,  20,  24,  28,  33,  38,  45,
        52,  60,  69,  80,  91, 104, 119, 135, 154, 174, 198, 200])

In [12]:
F_DFA, DCCA, P_DCCA, DMCx2= zb.dmcx2(int_mat, tws, dmcx2_of='all-full' )

<class 'numpy.ndarray'>


In [13]:
F_DFA

array([[0.15615254, 0.15018482, 0.15707912, 0.15066541, 0.15355686,
        0.15222981, 0.15064638, 0.15311393],
       [0.17587589, 0.1707751 , 0.17636604, 0.16991378, 0.17366069,
        0.17206673, 0.17037051, 0.17321206],
       [0.20837099, 0.20542097, 0.20799352, 0.20227891, 0.20761967,
        0.20457293, 0.20293583, 0.2057774 ],
       [0.23491451, 0.23410238, 0.23562799, 0.2294838 , 0.23583657,
        0.23191739, 0.23097623, 0.23271742],
       [0.25748108, 0.25791032, 0.26069823, 0.25246409, 0.26004284,
        0.25628755, 0.25572379, 0.25658363],
       [0.27769776, 0.27865788, 0.28348222, 0.27272525, 0.28204098,
        0.27797295, 0.2777773 , 0.27838447],
       [0.30613563, 0.3071564 , 0.31441752, 0.30033173, 0.31282989,
        0.30677169, 0.30681222, 0.30753127],
       [0.34207242, 0.34148619, 0.35100548, 0.33421896, 0.35031402,
        0.34016016, 0.33974886, 0.34146849],
       [0.37565777, 0.37263764, 0.38323745, 0.3659799 , 0.38357581,
        0.3700935 , 0.368355

In [14]:
print(DCCA)

[[ 4.79065105e-04  1.49144680e-03 -1.11812955e-03 -1.37396585e-03
   1.18363440e-04  7.15869731e-04 -2.78424815e-04 -8.85361974e-04
   7.47635581e-04 -5.10687831e-04  6.81494371e-04  3.16965440e-05
   7.71011211e-05 -2.15725194e-04  2.24827851e-04 -3.91831768e-04
  -6.28535672e-04  5.36539842e-04  2.86996563e-05  1.44640396e-05
   5.05019497e-04  3.49972221e-04  6.08873793e-04  1.42233111e-04
  -2.28755977e-04  1.11250386e-03 -5.52992749e-05  4.43180446e-04]
 [ 6.19031795e-04  1.70373555e-03 -1.11825348e-03 -1.81615399e-03
   2.14522261e-04  7.98379365e-04 -3.37656685e-04 -1.20114312e-03
   6.75686527e-04 -2.00947828e-04  9.66147027e-04  1.83521146e-05
  -5.57514561e-06 -5.20793238e-05  4.59382138e-04 -3.42887356e-04
  -8.14165030e-04  6.46647885e-04 -2.93670934e-04 -9.97678268e-06
   6.26461087e-04  9.58721268e-05  5.80090188e-04  2.04791147e-04
  -2.00752908e-04  1.42715464e-03 -2.97933581e-04  4.92287023e-04]
 [ 9.27163578e-04  1.80899946e-03 -1.06037848e-03 -2.55265209e-03
   3.643

In [15]:
P_DCCA

array([[[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00, ...,
          1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
        [ 2.04276987e-02,  2.06101944e-02,  2.16607920e-02, ...,
          4.98928879e-02,  8.17860732e-02,  8.42569865e-02],
        [ 6.08051345e-02,  5.49263719e-02,  4.17398989e-02, ...,
         -2.67731586e-02, -5.28502585e-02, -5.46282702e-02],
        ...,
        [ 4.97930611e-03,  7.08874147e-03,  8.54741273e-03, ...,
         -1.96307482e-02, -1.02320373e-02, -9.84197137e-03],
        [ 3.04317036e-02,  2.66445601e-02,  2.31817377e-02, ...,
         -7.44389766e-02, -1.07167537e-01, -1.10332683e-01],
        [-1.16451257e-02, -1.10838571e-02, -1.13414161e-02, ...,
          4.18464811e-02,  5.78303559e-02,  5.91617086e-02]],

       [[ 2.04276987e-02,  2.06101944e-02,  2.16607920e-02, ...,
          4.98928879e-02,  8.17860732e-02,  8.42569865e-02],
        [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00, ...,
          1.00000000e+00,  1.00000000e

In [16]:
DMCx2.max(), DMCx2.min(), DMCx2

(np.float64(0.12564509558916861),
 np.float64(0.0010857278830506555),
 array([[0.01110763, 0.00438403, 0.00695559, 0.00419698, 0.00476888,
         0.00417548, 0.00504021, 0.00142139],
        [0.0097155 , 0.00377062, 0.0064403 , 0.00265524, 0.00457585,
         0.00405914, 0.00476811, 0.00108573],
        [0.00761151, 0.00442157, 0.00612524, 0.00281904, 0.0060495 ,
         0.00438664, 0.00430681, 0.0015598 ],
        [0.00556982, 0.00510904, 0.0066833 , 0.00471207, 0.00828331,
         0.00472941, 0.00419081, 0.00240423],
        [0.00428282, 0.00480518, 0.00665639, 0.0074072 , 0.00976276,
         0.0051777 , 0.00490328, 0.0031284 ],
        [0.00347535, 0.00395336, 0.00590403, 0.01004908, 0.01050379,
         0.00547303, 0.00628995, 0.00390982],
        [0.00280238, 0.0031996 , 0.00516425, 0.01220583, 0.01083985,
         0.005332  , 0.00815638, 0.00454469],
        [0.00329933, 0.00356151, 0.00536084, 0.01216221, 0.01092846,
         0.00495058, 0.00883264, 0.00535296],
        [0