In [1]:
import numpy as np
#import pandas as pd
try:
    from zebende import zebende as zb
except:
    from importlib.machinery import SourceFileLoader
    zb = SourceFileLoader("zebende", ".././zebende/__init__.py").load_module()


In [2]:
mat = np.random.random(size=(800,8))
mat

array([[0.21189495, 0.91088907, 0.75326131, ..., 0.52451098, 0.83875099,
        0.06584895],
       [0.86862533, 0.15334915, 0.20097583, ..., 0.06768633, 0.78918246,
        0.25959217],
       [0.34680075, 0.82466522, 0.77299287, ..., 0.7594768 , 0.78233529,
        0.97163821],
       ...,
       [0.73503938, 0.06980199, 0.73962243, ..., 0.94894003, 0.82198776,
        0.45247976],
       [0.40712997, 0.94718556, 0.65817748, ..., 0.26003144, 0.24388271,
        0.47545001],
       [0.76464377, 0.05229727, 0.49961029, ..., 0.59329989, 0.66895069,
        0.7072073 ]])

In [3]:
int_mat = zb.integrated_series(mat)
print(int_mat)

[[-2.87030576e-01  4.11450250e-01  2.52162763e-01 ...  7.02389703e-04
   3.50184889e-01 -4.30754628e-01]
 [ 8.26692334e-02  6.53605821e-02 -4.79599537e-02 ... -4.55419870e-01
   6.50801250e-01 -6.67766040e-01]
 [-6.94555421e-02  3.90586985e-01  2.23934364e-01 ... -2.19751660e-01
   9.44570445e-01 -1.92731411e-01]
 ...
 [-1.73922696e-01 -6.05193790e-04 -1.55590673e-01 ...  1.94285847e-01
   6.42987969e-02 -1.89450150e-01]
 [-2.65718249e-01  4.47141551e-01  1.48825611e-03 ... -6.94912975e-02
  -1.80384589e-01 -2.10603721e-01]
 [-7.68607400e-13 -2.97539771e-14  2.74003042e-13 ... -4.83613150e-13
  -1.16795462e-13 -2.63511435e-13]]


In [4]:
tws = zb.time_windows(4, 200)
tws

array([  4,   5,   7,   9,  11,  13,  16,  20,  24,  28,  33,  38,  45,
        52,  60,  69,  80,  91, 104, 119, 135, 154, 174, 198, 200])

In [5]:
F_DFA, DCCA, P_DCCA = zb.p_dcca(int_mat, tws)

In [6]:
F_DFA

array([[0.15181682, 0.15227654, 0.15230888, 0.14916626, 0.15478845,
        0.15542307, 0.15387266, 0.15245502],
       [0.17236459, 0.17078713, 0.17124263, 0.16761457, 0.17441521,
        0.17646925, 0.17395468, 0.1703336 ],
       [0.20715845, 0.20150553, 0.20253443, 0.1995005 , 0.2059274 ,
        0.21092309, 0.20771284, 0.20042405],
       [0.2368405 , 0.22721458, 0.22878024, 0.22771935, 0.23277618,
        0.23821564, 0.23611701, 0.22631487],
       [0.26256521, 0.25070722, 0.25170499, 0.25354594, 0.25588361,
        0.26172194, 0.25961715, 0.24975697],
       [0.28606918, 0.27263809, 0.27172876, 0.27648653, 0.27604979,
        0.28257123, 0.27869584, 0.27138953],
       [0.31925595, 0.30456272, 0.29920626, 0.30657554, 0.30249562,
        0.31103221, 0.30402506, 0.3022079 ],
       [0.35949195, 0.34577244, 0.33162217, 0.34091067, 0.33436816,
        0.34692377, 0.33692079, 0.34065619],
       [0.39561852, 0.38404795, 0.35953065, 0.37084636, 0.36097724,
        0.38003173, 0.368708

In [7]:
print(DCCA)

[[-1.44663118e-03 -4.18646874e-04  7.85120298e-04 -9.40577822e-04
   1.86648402e-03  8.37777327e-04  7.03299943e-04  3.44715801e-04
   1.93223417e-03  2.24249938e-03 -1.12581659e-03 -6.09742619e-04
   5.03880878e-04  7.69841756e-04  1.39981868e-03  4.12622281e-04
  -5.69308896e-04 -8.96646901e-05  1.38156230e-03 -1.14850551e-03
  -1.45070293e-04  4.36250229e-04  2.42353803e-04  1.07976472e-04
  -4.01425685e-04 -4.30455204e-04  7.10290477e-04 -2.09429170e-04]
 [-1.79587062e-03 -5.13145682e-04  9.04334462e-04 -8.27745991e-04
   2.28723837e-03  5.75899279e-04  9.76850997e-04  4.42985664e-04
   1.81063765e-03  2.69069329e-03 -1.86033450e-03 -7.52579619e-04
   5.95808845e-04  1.23881800e-03  1.76244521e-03  3.78992911e-04
  -7.27157172e-04 -4.39401413e-04  1.53088834e-03 -1.80150463e-03
  -4.91536290e-04  2.15538175e-04  2.95460965e-04  3.94862337e-05
  -6.71305054e-04 -3.90109315e-04  8.07312300e-04 -7.52472926e-04]
 [-2.15899360e-03 -2.34834319e-04  1.60650950e-03 -5.45392666e-04
   3.023

In [8]:
P_DCCA

array([[-6.25755895e-02, -1.81051752e-02,  3.46693519e-02,
        -4.00254572e-02,  7.91022644e-02,  3.58630523e-02,
         3.03863805e-02,  1.48628798e-02,  8.50660318e-02,
         9.51394848e-02, -4.75684696e-02, -2.60226844e-02,
         2.17046688e-02,  3.38848548e-02,  5.93755984e-02,
         1.74305850e-02, -2.42918877e-02, -3.86148622e-03,
         5.98358312e-02, -4.95389744e-02, -6.32042703e-03,
         1.91833012e-02,  1.00738578e-02,  4.53345298e-03,
        -1.70108057e-02, -1.79991095e-02,  2.99763528e-02,
        -8.92758468e-03],
       [-6.10059025e-02, -1.73852423e-02,  3.13017975e-02,
        -2.75337070e-02,  7.51959301e-02,  1.92071257e-02,
         3.32720798e-02,  1.51468612e-02,  6.32505997e-02,
         9.03284799e-02, -6.17258180e-02, -2.53315172e-02,
         2.04810150e-02,  4.31602413e-02,  5.90091540e-02,
         1.25415195e-02, -2.44107036e-02, -1.50643097e-02,
         5.23657595e-02, -6.09052290e-02, -1.68580649e-02,
         7.54939443e-03,  9.59

In [9]:
arr_tot = []

arr_1 = np.sort([2,1])
arr_2 = np.sort(np.array([2,1]))
arr_3 = np.sort(np.array([2,3]))
arr_list = [arr_1, arr_2, arr_3]
for i in arr_list:
    if   True:
        arr_tot.append(i)
    print(arr_tot)
arr_tot

[array([1, 2])]
[array([1, 2]), array([1, 2])]
[array([1, 2]), array([1, 2]), array([2, 3])]


[array([1, 2]), array([1, 2]), array([2, 3])]

In [10]:
# importing package 
import numpy as np

# create numpy array 
arr = np.array([[1, 2, 3, 4, 5], 
				[6, 7, 8, 9, 10], 
				[11, 12, 13, 14, 15], 
				[16, 17, 18, 19, 20] 
				]) 

# view array 
print(np.array(arr.tolist())) 

# check for some lists 
print([1, 2, 3, 4, 5] in arr.tolist()) 
print([16, 17, 20, 19, 18] in arr.tolist()) 
print([3, 2, 5, -4, 5] in arr.tolist()) 
print([11, 12, 13, 14, 15] in arr.tolist()) 


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
True
False
False
True


In [11]:
arr = np.random.randint(10, size=(4,8))

In [12]:
arr

array([[3, 0, 9, 5, 7, 8, 4, 0],
       [7, 3, 4, 2, 1, 7, 9, 2],
       [7, 9, 7, 6, 4, 1, 6, 5],
       [0, 6, 5, 8, 6, 9, 7, 9]], dtype=int32)

In [13]:
arr.sort()

In [14]:
from itertools import combinations
import numpy as np


def pdcca_of_from_dmcx2_of(dmc_of):
    if type(dmc_of) == np.ndarray:
        dmc_of = dmc_of.tolist()
    out = []
    for i in range(len(dmc_of)):
        temp = list(combinations(dmc_of[i],2))
        for j in temp:
            j = list(j)

            j.sort()

            if not(j in out):
                out.append(j)
    return np.array(out)

In [15]:
dmc_of = np.array([[1,3,4,5], [0,4,3,5]])

dmc_of.max(), dmc_of.min(), type(dmc_of)

(np.int64(5), np.int64(0), numpy.ndarray)

In [16]:
test = pdcca_of_from_dmcx2_of(dmc_of)
test,type(dmc_of)

(array([[1, 3],
        [1, 4],
        [1, 5],
        [3, 4],
        [3, 5],
        [4, 5],
        [0, 4],
        [0, 3],
        [0, 5]]),
 numpy.ndarray)

In [17]:
import numpy as np


def dcca_of_from_dmcx2_of(data):
    temp = np.arange(data.shape[1])

In [18]:
dcca_of_from_dmcx2_of(mat)

In [19]:
a,b = 2
a,b

TypeError: cannot unpack non-iterable int object

In [ ]:
arr = np.array([2,4,5]).reshape(1,3)
arr 

In [ ]:
mat=np.random.random(size=(3,3))
mat

In [ ]:
np.matmul(np.matmul(arr, np.linalg.inv(mat)), arr.T)

In [ ]:


dmc_of=np.array([[1,2,4,3], [3,5,4,7], [4,2,3,1]])
dmc_of

In [ ]:

def ordering_x_dmcx2_of(dmcx2_of):
    y_serie = dmcx2_of[:,0]
    x_series = np.sort(dmcx2_of[:, 1:], axis=1)
    print(x_series, y_serie)
    out =  np.c_[ y_serie, x_series ] 
    return out 

In [ ]:
dmcx2_of =ordering_x_dmcx2_of(dmc_of)
dmcx2_of


In [ ]:
dmcx2_mat = np.random.randint(16*16).reshape(16,16)

for i in range(dmcx2_mat.shape[0]):
    dmcx2_mat[i,i]=1

dmcx2_mat 


In [ ]:
y_indexes = dmcx2_of[1,0:1]
x_indexes = dmcx2_of[1, 1:]
mat_x = dmcx2_mat[np.ix_(x_indexes, x_indexes)]
vec_y = dmcx2_mat[np.ix_(y_indexes, x_indexes)]
print(mat_x, '\n ----- \n',vec_y)
vec_y @ mat_x @ vec_y.T

In [ ]:
[[1.         0.00250678 0.29712539]
 [0.57179    1.         0.65112084]
 [0.92882498 0.42005626 1.        ]] 

 [[0.22316962 0.19418629 0.16270637]]
array([[0.21723419]])