In [1]:
import numpy as np
#import pandas as pd
try:
    from zebende import zebende as zb
except:
    print('Exception')
    from importlib.machinery import SourceFileLoader
    zb = SourceFileLoader("zebende", ".././zebende/__init__.py").load_module()


Exception


In [2]:
mat = np.random.random(size=(2_000,8))
mat

array([[0.8994353 , 0.91007168, 0.47340622, ..., 0.98472002, 0.4630912 ,
        0.00300149],
       [0.67839589, 0.08017382, 0.96150353, ..., 0.5314842 , 0.18208887,
        0.13648971],
       [0.30848217, 0.94037939, 0.1566104 , ..., 0.50544191, 0.14348528,
        0.86823867],
       ...,
       [0.05980034, 0.82272428, 0.63910046, ..., 0.12473694, 0.18250767,
        0.66909928],
       [0.03426036, 0.50739177, 0.96412949, ..., 0.35341201, 0.24043568,
        0.44412886],
       [0.67425712, 0.37874157, 0.00188132, ..., 0.10420086, 0.25216999,
        0.83178129]], shape=(2000, 8))

In [3]:
int_mat, med = zb.integrated_series(mat.T, axis=0, return_mean = True)
print(int_mat.shape, med.shape)
print(int_mat)


(8, 2000) (8,)
[[ 4.00694941e-01  5.80350469e-01  3.90092279e-01 ...  2.88963245e-01
  -1.75516758e-01 -2.61679567e-13]
 [ 4.10013323e-01 -9.87121344e-03  4.30449824e-01 ...  1.13983368e-01
   1.21316788e-01  3.29070104e-13]
 [-2.47291917e-02  4.38638926e-01  9.71139145e-02 ...  3.02600234e-02
   4.96254097e-01  1.11011200e-12]
 ...
 [ 4.86868621e-01  5.20501425e-01  5.28091941e-01 ...  5.38089932e-01
   3.93650542e-01 -2.85771407e-13]
 [-3.25139530e-02 -3.46030230e-01 -6.98150100e-01 ...  4.98604633e-01
   2.43435164e-01 -5.97299987e-13]
 [-5.01417940e-01 -8.69347659e-01 -5.05528416e-01 ... -2.67071295e-01
  -3.27361864e-01  2.65010236e-13]]


In [4]:
int_mat_1, med_1 = zb.integrated_series(mat, axis=1, return_mean = True)
print(int_mat_1.shape, med_1.shape)
print(int_mat_1)

(2000, 8) (8,)
[[ 4.00694941e-01  4.10013323e-01 -2.47291917e-02 ...  4.86868621e-01
  -3.25139530e-02 -5.01417940e-01]
 [ 5.80350469e-01 -9.87121344e-03  4.38638926e-01 ...  5.20501425e-01
  -3.46030230e-01 -8.69347659e-01]
 [ 3.90092279e-01  4.30449824e-01  9.71139145e-02 ...  5.28091941e-01
  -6.98150100e-01 -5.05528416e-01]
 ...
 [ 2.88963245e-01  1.13983368e-01  3.02600234e-02 ...  5.38089932e-01
   4.98604633e-01 -2.67071295e-01]
 [-1.75516758e-01  1.21316788e-01  4.96254097e-01 ...  3.93650542e-01
   2.43435164e-01 -3.27361864e-01]
 [-2.61679567e-13  3.29070104e-13  1.11011200e-12 ... -2.85771407e-13
  -5.97299987e-13  2.65010236e-13]]


In [5]:
assert (int_mat_1.T == int_mat).all()

In [6]:
assert (med == med_1).all()

In [7]:
tws = zb.time_windows(4, 200)
tws

array([  4,   5,   7,   9,  11,  13,  16,  20,  24,  28,  33,  38,  45,
        52,  60,  69,  80,  91, 104, 119, 135, 154, 174, 198, 200])

In [8]:
F_DFA, DCCA, P_DCCA, DMCx2= zb.dmcx2(int_mat, tws, dmcx2_of='all-full' )

<class 'numpy.ndarray'>


In [9]:
F_DFA

array([[0.15601725, 0.15291921, 0.15372918, 0.15151304, 0.15170058,
        0.1565739 , 0.15305788, 0.15374372],
       [0.1750938 , 0.17164698, 0.17237448, 0.17044863, 0.17022666,
        0.17651962, 0.17202186, 0.17334246],
       [0.20751587, 0.20183862, 0.20358102, 0.20278956, 0.20196313,
        0.20761962, 0.20340006, 0.20501411],
       [0.23516701, 0.22796066, 0.23047165, 0.23139787, 0.23007584,
        0.23118842, 0.22955059, 0.23144948],
       [0.25954668, 0.25161703, 0.25387818, 0.25645403, 0.25568072,
        0.25130546, 0.25272955, 0.25527026],
       [0.28125735, 0.27322793, 0.2745324 , 0.27907707, 0.27955783,
        0.26958787, 0.27431632, 0.27716146],
       [0.31031241, 0.30287848, 0.30314493, 0.30994267, 0.31227105,
        0.29491588, 0.30414856, 0.30669178],
       [0.34464542, 0.33929682, 0.33890424, 0.34825467, 0.34982012,
        0.32639653, 0.3408032 , 0.34064094],
       [0.3761214 , 0.37210419, 0.37206545, 0.38389291, 0.38193275,
        0.35575027, 0.373813

In [10]:
print(DCCA)

[[-4.60546956e-04 -2.76636207e-04  3.29108332e-04 -4.46237049e-04
  -1.13889895e-03  1.70265285e-04  3.21874705e-05  2.55394968e-04
  -3.23960809e-04 -8.16957461e-05  5.06623841e-04  5.00523562e-04
   8.09885105e-05 -7.24470151e-04  1.27038491e-04  1.42568322e-03
  -1.23147681e-04  3.59073705e-05  9.86539294e-04 -4.83827403e-04
  -1.58738117e-03 -1.53983129e-03 -4.81358582e-04 -7.39682348e-05
   2.53369159e-04 -7.01309907e-04 -5.27725735e-04 -4.35717255e-04]
 [-4.70251270e-04 -4.33519531e-04  5.15545572e-04 -6.49441169e-04
  -2.01473479e-03  1.65112788e-04  7.26205333e-05  3.97012187e-04
  -5.18467113e-04 -7.58779846e-05  9.21561797e-04  4.07296457e-04
   2.37117369e-04 -1.24507408e-03 -1.89693599e-04  1.85233839e-03
  -1.68838946e-04 -2.99877899e-05  1.49832494e-03 -4.56772869e-04
  -1.81806859e-03 -2.19011112e-03 -7.35246252e-04 -6.69003625e-05
   5.84496840e-04 -8.39282112e-04 -5.77405456e-04 -4.96895716e-04]
 [-1.64334025e-04 -3.99503538e-04  1.01750826e-03 -8.59281251e-04
  -3.347

In [11]:
P_DCCA

array([[[ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00, ...,
          1.00000000e+00,  1.00000000e+00,  1.00000000e+00],
        [-1.93036422e-02, -1.56467104e-02, -3.92348420e-03, ...,
         -1.32641314e-01, -1.51406823e-01, -1.52556216e-01],
        [-1.15340039e-02, -1.43636539e-02, -9.45653505e-03, ...,
          1.11257490e-01,  1.15819892e-01,  1.16429956e-01],
        ...,
        [-4.66222470e-02, -6.51859713e-02, -7.77002695e-02, ...,
          3.01678450e-03,  7.99906103e-03,  8.36933351e-03],
        [ 7.13013580e-03,  5.48183943e-03,  5.07484199e-03, ...,
         -5.14296311e-02, -5.07565118e-02, -5.06668728e-02],
        [ 1.34188980e-03,  2.39267491e-03,  1.15705781e-02, ...,
          9.99573307e-02,  8.55877130e-02,  8.44176557e-02]],

       [[-1.93036422e-02, -1.56467104e-02, -3.92348420e-03, ...,
         -1.32641314e-01, -1.51406823e-01, -1.52556216e-01],
        [ 1.00000000e+00,  1.00000000e+00,  1.00000000e+00, ...,
          1.00000000e+00,  1.00000000e

In [12]:
DMCx2.max(), DMCx2.min(), DMCx2

(np.float64(0.11366895578178134),
 np.float64(0.0009269304028528901),
 array([[0.00320528, 0.0015188 , 0.0046485 , 0.01288005, 0.00287979,
         0.0082236 , 0.00672282, 0.00567005],
        [0.00540951, 0.00176744, 0.00569881, 0.01484409, 0.00437135,
         0.01058117, 0.00540086, 0.00698879],
        [0.00744355, 0.00269281, 0.00720685, 0.01690643, 0.0071073 ,
         0.01335646, 0.00256495, 0.00948402],
        [0.00804955, 0.00486056, 0.00772733, 0.01772538, 0.00872346,
         0.01434914, 0.00104063, 0.01187645],
        [0.00872966, 0.00753517, 0.00752639, 0.01703471, 0.00957481,
         0.01500762, 0.00092693, 0.0124342 ],
        [0.00942408, 0.00999572, 0.00753913, 0.01544171, 0.01028069,
         0.01575576, 0.00132094, 0.01158636],
        [0.01023677, 0.012764  , 0.00895586, 0.01408573, 0.01164345,
         0.01698826, 0.00208308, 0.01001317],
        [0.01052693, 0.01351922, 0.0122444 , 0.01483824, 0.01369296,
         0.01702507, 0.00310838, 0.0090402 ],
        [0